---
title: "mpls-violent-crimes.csv"
format:
  html:
    theme: 
      - lumen
    css: ["../assets/codebooks.css"]
    code-copy: true
    code-fold: true
    highlight-style: zenburn
    df-print: paged
    linkcolor: '#ff851b'
date: "07-28-2022"
bibliography: '../assets/data.bib'
csl: '../assets/apa-single-spaced.csl'
---


```{r}
#| echo: false
source("../assets/codebook-setup.R")
```

---


The [mpls-violent-crime.csv](https://raw.githubusercontent.com/zief0002/pensive-giraffe/main/data/mpls-violent-crime.csv) file contains data collected from the Minneapolis Police Department and reported by the [Star Tribune](http://www.startribune.com/a-deeper-look-at-minneapolis-crime-rates/493163741/) on  The two attributes in this file are:

- `year`: Year
- `crime_rate`: Violent crime rate per 100,000 people


<br />


### Preview

```{r}
#| echo: true

# Import data
crime = readr::read_csv(file = "https://raw.githubusercontent.com/zief0002/pensive-giraffe/main/data/mpls-violent-crime.csv")

# View data
crime
```


<!-- ### References -->

<!-- <p style="padding-left: 50px; text-indent: -50px;"> -->

