---
title: "Calendar"
---


The calendar below lists the tentative course topics. The dates listed are subject to change at the instructor's discretion.

As part of the course, there are several articles, papers and technical reports that you will need to read during the semester. Most of the articles themselves are accessible through the University of Minnesota library website (http://www.lib.umn.edu). In order to access the full text of some of the articles, you will need to log in using your University x500 username and password. More detailed information, including references or links to specific readings, are linked under the day's "Reading".

<br /><br />


<br />


<table class="table">

<tr>
<th style="width:5%;text-align:center"></th>
<th style="width:10%;">Date</th>
<th style="width:10%;text-align:center">Reading</th>
<th style="width:65%;">Topic</th>
<th style="width:10%;text-align:center">Notes</th>
</tr>
</thead>


<tbody>

<!-- <span style="margin-left:5px; color:#5a067d;font-size:12px;">*[Notes and Script file updated 09-24-2019]*</span></td> -->


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Sept. 05</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="readings/00-welcome-to-8264.html"><span class="fa fa-book"></span></a>
</td>
<td>Welcome to EPsy 8264</td>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
</tr>


<!-- Unit 01: MATHEMATICAL AND COMPUTATIONAL FOUNDATIONS -->

<tr>
<td colspan="5"><b>Unit 01: Mathematical and Computational Foundations</b></td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Sept. 07</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a class="my-link" href="readings/01-01-introduction-to-matrix-algebra.html"><span class="fa fa-book"></span></a>
</td>
<td style="vertical-align:middle;" rowspan="2">Introduction to Matrix Algebra</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a class = "my-link" href="worksheets/01-01-introduction-to-matrix-algebra.html"><span class="fas fa-link"></span></a>
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Sept. 12</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Sept. 14</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a class="my-link" href="readings/01-02-ols.html"><span class="fa fa-book"></span></a>
</td>
<td style="vertical-align:middle;" rowspan="2">OLS Regression using Matrices and its Properties</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a class = "my-link" href="notes/01-02-ols-regression.html"><span class="fas fa-link"></span></a>
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Sept. 19</td>
</tr>


<!-- Unit 02: SIMULATION -->


<tr>
<td colspan="5"><b>Unit 02: Simulation</b></td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Sept. 21</td>
<td align="center" style="vertical-align:middle;" rowspan="3">
  <a class="my-link" href="readings/02-01-simulating-from-the-regression-model.html"><span class="fa fa-book"></span></a>
</td>
<td style="vertical-align:middle;" rowspan="3">Simulating from the Regression Model</td>
<td align="center" style="vertical-align:middle;" rowspan="3">
  <a class = "my-link" href="notes/02-01-simulating-from-the-regression-model.html"><span class="fas fa-link"></span></a>
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Sept. 26</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Sept. 28</td>
</tr>


<!-- Unit 03:PATH ANALYSIS -->


<tr>
<td colspan="5"><b>Unit 03: Path Analysis</b></td>
</tr>

<!-- CUT THIS: Add to READING  -->


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Oct. 03</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="readings/03-01-regression-from-summary-measures.html"><span class="fa fa-book"></span></a>
</td>
<td style="vertical-align:middle;">Regression from Summary Measures</td>
<td align="center" style="vertical-align:middle;">
  <a class = "my-link" href="notes/03-01-regression-from-summary-measures.html"><span class="fas fa-link"></span></a>
</td>
</tr>



<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Oct. 05</td>
<td align="center" style="vertical-align:middle;"></td>
<td style="vertical-align:middle;">Path Analysis</td>
<td align="center" style="vertical-align:middle;">
  <a class = "my-link" href="notes/03-02-path-analysis.html"><span class="fas fa-link"></span></a>
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;" >&nbsp;</td>
<td>Oct. 10</td>
<td align="center" style="vertical-align:middle;">
  <!-- <a class="my-link" href="readings/13-cross-validation.html"><span class="fa fa-book"></span></a> -->
</td>
<td style="vertical-align:middle;">More Path Models</td>
<td align="center" style="vertical-align:middle;">
  <a class = "my-link" href="notes/03-03-more-path-analysis.html"><span class="fas fa-link"></span></a>
</td>
</tr>

<!-- <tr> -->
<!-- <td align="center" style="vertical-align:middle;">&nbsp;</td> -->
<!-- <td>Dec. 13</td> -->
<!-- </tr> -->



<!-- Unit 04: REGRESSION DIAGNOSTICS -->


<!-- <tr> -->
<td colspan="5"><b>Unit 04: Regression Diagnostics</b></td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Oct. 12</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a class="my-link" href="readings/04-01-regression-diagnostics.html"><span class="fa fa-book"></span></a>
</td>
<td style="vertical-align:middle;" rowspan="2">Regression Diagnostics</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a class = "my-link" href="notes/04-01-regression-diagnostics.html"><span class="fas fa-link"></span></a>
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Oct. 17</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Oct. 19</td>
<td align="center" style="vertical-align:middle;"></td>
<td style="vertical-align:middle;">NO CLASS---Mental Health Day 🛌 🍷</td>
<td align="center" style="vertical-align:middle;"></td>
</tr>


<!-- Unit 05: HETEROSKEDASTICITY-->


<tr>
<td colspan="5"><b>Unit 05: Tools for Dealing with Heteroskedasticity</b></td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Oct. 24</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="readings/05-01-variance-stabilizing-transformations.html"><span class="fa fa-book"></span></a>
</td>
<td style="vertical-align:middle;">Variance Stabilizing Transformations</td>
<td align="center" style="vertical-align:middle;">
  <a class = "my-link" href="notes/05-01-tools-for-dealing-with-heteroskedasticity.html"><span class="fas fa-link"></span></a>
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Oct. 26</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="readings/05-02-wls-and-sandwich-estimation.html
  "><span class="fa fa-book"></span></a>
</td>
<td style="vertical-align:middle;">Weighted Least Squares (WLS) and Sandwich Estimation</td>
<td align="center" style="vertical-align:middle;">
  <a class = "my-link" href="notes/05-01-tools-for-dealing-with-heteroskedasticity.html"><span class="fas fa-link"></span></a>
</td>
</tr>



<!-- Unit 06: COLLINEARITY -->


<tr>
<td colspan="5"><b>Unit 06: Diagnosing Collinearity and Tools for Dealing with It</b></td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Oct. 31</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a class="my-link" href="readings/06-01-diagnosing-collinearity.html"><span class="fa fa-book"></span></a>
</td>
<td style="vertical-align:middle;" rowspan="2">Diagnosing Collinearity</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a class = "my-link" href="notes/06-01-diagnosing-collinearity.html"><span class="fas fa-link"></span></a>
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Nov. 02</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Nov. 07</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a class="my-link" href="readings/06-02-pca-via-spectral-decomposition.html"><span class="fa fa-book"></span></a>
</td>
<td style="vertical-align:middle;" rowspan="2">Principal Components Analysis via Spectral Decomposition</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a class = "my-link" href="notes/06-02-pca-via-spectral-decomposition.html"><span class="fas fa-link"></span></a>
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Nov. 09</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Nov. 14</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="readings/06-03-pca-via-svd.html"><span class="fa fa-book"></span></a>
</td>
<td style="vertical-align:middle;">Principal Components Analysis via Singular Value Decomposition</td>
<td align="center" style="vertical-align:middle;">
  <a class = "my-link" href="notes/06-03-pca-via-svd.html"><span class="fas fa-link"></span></a>
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Nov. 16</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a class="my-link" href="readings/06-04-biased-estimation-ridge-regression.html"><span class="fa fa-book"></span></a>
</td>
<td style="vertical-align:middle;" rowspan="2">Biased Estimation: Ridge Regression</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a class = "my-link" href="notes/06-04-biased-estimation-ridge-regression.html"><span class="fas fa-link"></span></a>
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Nov. 21</td>
</tr>


<!-- <tr> -->
<!-- <td align="center" style="vertical-align:middle;">&nbsp;</td> -->
<!-- <td>Nov. 21</td> -->
<!-- <td align="center" style="vertical-align:middle;"> -->
<!--   <a class="my-link" href="readings/06-04-biased-estimation-ridge-regression.html"><span class="fa fa-book"></span></a> -->
<!-- </td> -->
<!-- <td style="vertical-align:middle;">Biased Estimation: Ridge Regression  -->
<!-- <!-- <br /> <span style="margin-left:20px; color:red;">*[Notes Updated 11-10-2022]*</span> --> -->
<!-- </td> -->
<!-- <td align="center" style="vertical-align:middle;"> -->
<!--   <a class = "my-link" href="notes/06-04-biased-estimation-ridge-regression.html"><span class="fas fa-link"></span></a> -->
<!-- </td> -->
<!-- </tr> -->

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Nov. 23</td>
<td align="center" style="vertical-align:middle;"></td>
<td style="vertical-align:middle;">NO CLASS&mdash;Thanksgiving Break 🦃 🌽 🥧</td>
<td align="center" style="vertical-align:middle;"></td>
</tr>



<!-- Unit 07: MODEL SELECTION -->


<tr>
<td colspan="5"><b>Unit 07: Model Selection</b></td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Nov. 28</td>
<td align="center" style="vertical-align:middle;"></td>
<td style="vertical-align:middle;">Model Selection Activity</td>
<td align="center" style="vertical-align:middle;">
  <a class = "my-link" href="worksheets/07-01-model-selection.html"><span class="fas fa-link"></span></a>
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Nov. 30</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="readings/07-02-model-selection.html"><span class="fa fa-book"></span></a>
</td>
<td style="vertical-align:middle;">Model Selection: The 'Vintage' Methods</td>
<td align="center" style="vertical-align:middle;">
  <a class = "my-link" href="files/07-02-model-selection.pdf"><span class="fas fa-link"></span></a>
</td>
</tr>



<tr>
<td align="center" style="vertical-align:middle;" >&nbsp;</td>
<td>Dec. 05</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a class="my-link" href="readings/07-03-cross-validation.html"><span class="fa fa-book"></span></a>
</td>
<td style="vertical-align:middle;" rowspan="2">Model Selection: Cross-Validation Methods</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a class = "my-link" href="notes/07-03-cross-validation.html"><span class="fas fa-link"></span></a>
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Dec. 07</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Dec. 12</td>
<td align="center" style="vertical-align:middle;"></td>
<td style="vertical-align:middle;">TBD</td>
<td align="center" style="vertical-align:middle;"></td>
</tr>


</tbody>
</table>    


