<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2023-08-02">

<title>EPsy 8264 - 🎶 Path Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
<script src="https://kit.fontawesome.com/e5da75ca36.js" crossorigin="anonymous"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../assets/sticky-notes.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">EPsy 8264</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../schedule.html" rel="" target="">
 <span class="menu-text">Schedule</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../assignments.html" rel="" target="">
 <span class="menu-text">Assignments</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../data.html" rel="" target="">
 <span class="menu-text">Data</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">Instructor &amp; TA</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../mission-statements.html" rel="" target="">
 <span class="menu-text">Mission Statements</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../umn-policies.html" rel="" target="">
 <span class="menu-text">University Policies</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#what-are-path-diagrams" id="toc-what-are-path-diagrams" class="nav-link active" data-scroll-target="#what-are-path-diagrams">What are Path Diagrams?</a></li>
  <li><a href="#example" id="toc-example" class="nav-link" data-scroll-target="#example">Example</a></li>
  <li><a href="#simulating-data" id="toc-simulating-data" class="nav-link" data-scroll-target="#simulating-data">Simulating Data</a></li>
  <li><a href="#simulating-data-cntd." id="toc-simulating-data-cntd." class="nav-link" data-scroll-target="#simulating-data-cntd.">Simulating Data (cntd.)</a></li>
  <li><a href="#reading-a-path-diagram" id="toc-reading-a-path-diagram" class="nav-link" data-scroll-target="#reading-a-path-diagram">Reading a Path Diagram</a></li>
  <li><a href="#reading-a-path-diagram-cntd." id="toc-reading-a-path-diagram-cntd." class="nav-link" data-scroll-target="#reading-a-path-diagram-cntd.">Reading a Path Diagram (cntd.)</a></li>
  <li><a href="#two-example-path-diagrams" id="toc-two-example-path-diagrams" class="nav-link" data-scroll-target="#two-example-path-diagrams">Two Example Path Diagrams</a></li>
  <li><a href="#path-diagram-1" id="toc-path-diagram-1" class="nav-link" data-scroll-target="#path-diagram-1">Path Diagram 1</a></li>
  <li><a href="#estimating-path-coefficients-in-path-diagram-1" id="toc-estimating-path-coefficients-in-path-diagram-1" class="nav-link" data-scroll-target="#estimating-path-coefficients-in-path-diagram-1">Estimating Path Coefficients in Path Diagram 1</a></li>
  <li><a href="#weak-causal-ordering" id="toc-weak-causal-ordering" class="nav-link" data-scroll-target="#weak-causal-ordering">Weak Causal Ordering</a></li>
  <li><a href="#path-model-2-weak-causal-ordering" id="toc-path-model-2-weak-causal-ordering" class="nav-link" data-scroll-target="#path-model-2-weak-causal-ordering">Path Model 2: Weak Causal Ordering</a></li>
  <li><a href="#estimating-path-coefficients-in-a-weak-causal-model" id="toc-estimating-path-coefficients-in-a-weak-causal-model" class="nav-link" data-scroll-target="#estimating-path-coefficients-in-a-weak-causal-model">Estimating Path Coefficients in a Weak Causal Model</a></li>
  <li><a href="#example-of-the-tracing-rule" id="toc-example-of-the-tracing-rule" class="nav-link" data-scroll-target="#example-of-the-tracing-rule">Example of the Tracing Rule</a></li>
  <li><a href="#example-of-the-tracing-rule-cntd." id="toc-example-of-the-tracing-rule-cntd." class="nav-link" data-scroll-target="#example-of-the-tracing-rule-cntd.">Example of the Tracing Rule (cntd.)</a></li>
  <li><a href="#important-note-regarding-the-tracing-rule" id="toc-important-note-regarding-the-tracing-rule" class="nav-link" data-scroll-target="#important-note-regarding-the-tracing-rule">Important Note Regarding the Tracing Rule</a></li>
  <li><a href="#back-to-estimating-the-path-coeffients" id="toc-back-to-estimating-the-path-coeffients" class="nav-link" data-scroll-target="#back-to-estimating-the-path-coeffients">Back to Estimating the Path Coeffients</a></li>
  <li><a href="#your-turn" id="toc-your-turn" class="nav-link" data-scroll-target="#your-turn">Your Turn</a></li>
  <li><a href="#check-your-work" id="toc-check-your-work" class="nav-link" data-scroll-target="#check-your-work">Check Your Work</a></li>
  <li><a href="#check-your-work-1" id="toc-check-your-work-1" class="nav-link" data-scroll-target="#check-your-work-1">Check Your Work</a></li>
  <li><a href="#solving-for-p1-p2-and-p3" id="toc-solving-for-p1-p2-and-p3" class="nav-link" data-scroll-target="#solving-for-p1-p2-and-p3">Solving for p1, p2, and p3</a></li>
  <li><a href="#path-diagram-with-estimated-path-coefficients" id="toc-path-diagram-with-estimated-path-coefficients" class="nav-link" data-scroll-target="#path-diagram-with-estimated-path-coefficients">Path Diagram with Estimated Path Coefficients</a></li>
  <li><a href="#interpreting-path-coefficients" id="toc-interpreting-path-coefficients" class="nav-link" data-scroll-target="#interpreting-path-coefficients">Interpreting Path Coefficients</a></li>
  <li><a href="#interpreting-path-coefficients-cntd." id="toc-interpreting-path-coefficients-cntd." class="nav-link" data-scroll-target="#interpreting-path-coefficients-cntd.">Interpreting Path Coefficients (cntd.)</a></li>
  <li><a href="#estimating-path-coefficients-via-regression" id="toc-estimating-path-coefficients-via-regression" class="nav-link" data-scroll-target="#estimating-path-coefficients-via-regression">Estimating Path Coefficients via Regression</a></li>
  <li><a href="#estimating-path-coefficients-via-regression-cntd." id="toc-estimating-path-coefficients-via-regression-cntd." class="nav-link" data-scroll-target="#estimating-path-coefficients-via-regression-cntd.">Estimating Path Coefficients via Regression (cntd.)</a></li>
  <li><a href="#residual-variation" id="toc-residual-variation" class="nav-link" data-scroll-target="#residual-variation">Residual Variation</a></li>
  <li><a href="#estimating-residual-variation" id="toc-estimating-residual-variation" class="nav-link" data-scroll-target="#estimating-residual-variation">Estimating Residual Variation</a></li>
  <li><a href="#estimating-residual-variation-cntd." id="toc-estimating-residual-variation-cntd." class="nav-link" data-scroll-target="#estimating-residual-variation-cntd.">Estimating Residual Variation (cntd.)</a></li>
  <li><a href="#how-do-we-draw-path-diagram" id="toc-how-do-we-draw-path-diagram" class="nav-link" data-scroll-target="#how-do-we-draw-path-diagram">How Do We Draw Path Diagram?</a></li>
  <li><a href="#a-little-more-about-cause" id="toc-a-little-more-about-cause" class="nav-link" data-scroll-target="#a-little-more-about-cause">A Little More About Cause</a></li>
  <li><a href="#a-little-more-about-cause-cntd." id="toc-a-little-more-about-cause-cntd." class="nav-link" data-scroll-target="#a-little-more-about-cause-cntd.">A Little More About Cause (cntd.)</a></li>
  <li><a href="#requirements-for-cause" id="toc-requirements-for-cause" class="nav-link" data-scroll-target="#requirements-for-cause">Requirements for Cause</a></li>
  <li><a href="#including-time-precedence-in-the-path-diagram" id="toc-including-time-precedence-in-the-path-diagram" class="nav-link" data-scroll-target="#including-time-precedence-in-the-path-diagram">Including Time Precedence in the Path Diagram</a></li>
  <li><a href="#including-time-precedence-in-the-path-diagram-cntd." id="toc-including-time-precedence-in-the-path-diagram-cntd." class="nav-link" data-scroll-target="#including-time-precedence-in-the-path-diagram-cntd.">Including Time Precedence in the Path Diagram (cntd.)</a></li>
  <li><a href="#common-cause" id="toc-common-cause" class="nav-link" data-scroll-target="#common-cause">Common Cause</a></li>
  <li><a href="#common-cause-cntd." id="toc-common-cause-cntd." class="nav-link" data-scroll-target="#common-cause-cntd.">Common Cause (cntd.)</a></li>
  <li><a href="#common-cause-cntd.-1" id="toc-common-cause-cntd.-1" class="nav-link" data-scroll-target="#common-cause-cntd.-1">Common Cause (cntd.)</a></li>
  <li><a href="#non-recursive-models" id="toc-non-recursive-models" class="nav-link" data-scroll-target="#non-recursive-models">Non-Recursive Models</a></li>
  <li><a href="#under-identified-models" id="toc-under-identified-models" class="nav-link" data-scroll-target="#under-identified-models">Under-Identified Models</a></li>
  <li><a href="#over-identified-models" id="toc-over-identified-models" class="nav-link" data-scroll-target="#over-identified-models">Over-Identified Models</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="03-02-path-analysis.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">🎶 Path Analysis</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 2, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="what-are-path-diagrams" class="level2">
<h2 class="anchored" data-anchor-id="what-are-path-diagrams">What are Path Diagrams?</h2>
<p>Path diagrams are visual depictions of the hypothesized relationships between a set of variables. In this set of notes, we will introduce some of the ideas and concepts related to path diagrams, and the estimation of effects depicted in a path diagram (i.e., path analysis).</p>
<ul>
<li><a href="https://raw.githubusercontent.com/zief0002/redesigned-adventure/main/scripts/03-02-path-analysis.R">[R Script File]</a></li>
</ul>
</section>
<section id="example" class="level2">
<h2 class="anchored" data-anchor-id="example">Example</h2>
<p>To help us in this endeavor, we will consider three potential student-level variables for our path model:</p>
<ul>
<li>Achievement</li>
<li>Academic Ability</li>
<li>Motivation</li>
</ul>
</section>
<section id="simulating-data" class="level2">
<h2 class="anchored" data-anchor-id="simulating-data">Simulating Data</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load Libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Create correlation matrix</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>corrs <span class="ot">=</span> <span class="fu">matrix</span>(</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> <span class="fu">c</span>(</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="fl">1.000</span>, <span class="fl">0.737</span>, <span class="fl">0.255</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.737</span>, <span class="fl">1.000</span>, <span class="fl">0.205</span>,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.255</span>, <span class="fl">0.205</span>, <span class="fl">1.000</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">nrow =</span> <span class="dv">3</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Create mean vector</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>means <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>) </span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Set sample size</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">1000</span>           </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="simulating-data-cntd." class="level2">
<h2 class="anchored" data-anchor-id="simulating-data-cntd.">Simulating Data (cntd.)</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make simulation reproducible</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate the data and convert to data frame</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>sim_dat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(MASS<span class="sc">::</span><span class="fu">mvrnorm</span>(<span class="at">n =</span> <span class="dv">1000</span>, <span class="at">mu =</span> means, <span class="at">Sigma =</span> corrs, <span class="at">empirical =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">achievement =</span> X1,</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">ability =</span> X2, </span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">motivation =</span> X3</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="co"># View simulated data</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(sim_dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  achievement     ability  motivation
1  -0.5157929 -0.96667633  0.95967280
2  -0.1533491 -1.50764502  0.65576719
3  -0.4205593  0.97389153 -0.40326809
4   1.5952036  1.11549647  0.15201335
5   0.2921577  0.08731381  0.03244754
6  -0.9016836  0.15578506 -1.32479673</code></pre>
</div>
</div>
</section>
<section id="reading-a-path-diagram" class="level2">
<h2 class="anchored" data-anchor-id="reading-a-path-diagram">Reading a Path Diagram</h2>
<p>In a path diagram,</p>
<ul>
<li>Variables we have data on (i.e., manifest or measured variables) are represented by squares or rectangles.</li>
<li>Lines between the variables indicate a relationship between the two connected variables. The lines between the different variables are called paths.
<ul>
<li>If the path has an arrowhead on both sides, it indicates the two connected variables are related (i.e., correlated).</li>
<li>If the path has an arrowhead on only one side, it indicates a hypothesized causal relationship. The cause is in the direction of the arrow; that is, the hypothesized cause is at the butt end of the line, while the hypothesized effect is at the arrowhead side of the line.</li>
</ul></li>
</ul>
</section>
<section id="reading-a-path-diagram-cntd." class="level2">
<h2 class="anchored" data-anchor-id="reading-a-path-diagram-cntd.">Reading a Path Diagram (cntd.)</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../img/path-analysis-notes/10-symbols.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="two-example-path-diagrams" class="level2">
<h2 class="anchored" data-anchor-id="two-example-path-diagrams">Two Example Path Diagrams</h2>
<div class="columns">
<p>In both of the examples below, there are three manifest/measured variables (academic ability, motivation, and achievement) and three paths (p1, p2, and p3). The difference between the two is that in the right-hand diagram, there are hypothesized causal relationships, while in the left-hand diagram the relationships are not presumed to be causal.</p><div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../img/path-analysis-notes/01-correlation-path.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../img/path-analysis-notes/03-weak-causal-path.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="path-diagram-1" class="level2">
<h2 class="anchored" data-anchor-id="path-diagram-1">Path Diagram 1</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../img/path-analysis-notes/01-correlation-path.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<p>The model depicted in this path diagram posits that there are relationships between:</p>
<ul>
<li>Academic ability and achievement (p1);</li>
<li>Academic ability and motivation (p2); and</li>
<li>Motivation and achievement (p3).</li>
</ul>
<p>The double-headed arrows on the paths indicate that the variables are related (i.e., correlated), although there is no causal direction hypothesized.</p>
</div>
</div>
</section>
<section id="estimating-path-coefficients-in-path-diagram-1" class="level2">
<h2 class="anchored" data-anchor-id="estimating-path-coefficients-in-path-diagram-1">Estimating Path Coefficients in Path Diagram 1</h2>
<div class="columns">
<p>In a path analysis, one goal is to estimate path coefficients. In this model, since the paths represent the relationship between two variables, the path coefficients are simply the bivariate correlations between each set of variables.</p><div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute correlations</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>sim_dat <span class="sc">|&gt;</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">correlate</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  term        achievement ability motivation
  &lt;chr&gt;             &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;
1 achievement      NA       0.737      0.255
2 ability           0.737  NA          0.205
3 motivation        0.255   0.205     NA    </code></pre>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../img/path-analysis-notes/02-correlation-path-values.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="weak-causal-ordering" class="level2">
<h2 class="anchored" data-anchor-id="weak-causal-ordering">Weak Causal Ordering</h2>
<p>In path modeling, we often assert <em>weak causal ordering</em> on the variables in the model. With weak causal ordering, we are not saying <em>X</em> causes <em>Y</em>, but rather that <em>if</em> <em>X</em> and <em>Y</em> are casually related, one of these variables (typically <em>X</em>) is the cause of the other.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<div>
<pre class="mermaid mermaid-js">flowchart LR
  A[X] --&gt; B[Y]
</pre>
</div>
</div>
</div>
</div>
<p>In this model, the paths have arrows at only one end indicating the hypothesized causal relationship. The cause is in the direction of the arrow, that is the hypothesized cause is at the butt end of the line, while the hypothesized effect is at the arrowhead side of the line.</p>
<blockquote class="blockquote">
<p>Any weak causal model should be posited prior to collecting or looking at the data! Creating this model can also help you identify the data to collect.</p>
</blockquote>
</section>
<section id="path-model-2-weak-causal-ordering" class="level2">
<h2 class="anchored" data-anchor-id="path-model-2-weak-causal-ordering">Path Model 2: Weak Causal Ordering</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../img/path-analysis-notes/03-weak-causal-path.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<p>The model depicted in this path diagram posits the following causal relationships:</p>
<ul>
<li>If academic ability and achievement are causally related, then academic ability is the cause of achievement.</li>
<li>If academic ability and motivation are causally related, then academic ability is the cause of motivation.</li>
<li>If motivation and achievement are causally related, then motivation is the cause of achievement.</li>
</ul>
</div>
</div>
</section>
<section id="estimating-path-coefficients-in-a-weak-causal-model" class="level2">
<h2 class="anchored" data-anchor-id="estimating-path-coefficients-in-a-weak-causal-model">Estimating Path Coefficients in a Weak Causal Model</h2>
<p>Again, we would want to estimate the path coefficients shown in the diagram for the weak causal model. In causal models, the path coefficients are not necessarily the correlations. To find the path coefficients we need to use the <em>tracing rule</em>. The tracing rule indicates that:</p>
<blockquote class="blockquote">
<p>The correlation between two variables <em>X</em> and <em>Y</em> is equal to the sum of the possible products of all possible paths from each possible tracing from <em>X</em> to <em>Y</em>, with the following two exceptions:</p>
<ul>
<li>The same variable is not entered more than once in the same tracing.</li>
<li>A variable is not both entered and exited through an arrowhead.</li>
</ul>
</blockquote>
</section>
<section id="example-of-the-tracing-rule" class="level2">
<h2 class="anchored" data-anchor-id="example-of-the-tracing-rule">Example of the Tracing Rule</h2>
<p>As an example, consider all the tracings (routes) that allow us to start at the academic ability variable and go to the achievement variable in the path diagram at right.</p>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../img/path-analysis-notes/03-weak-causal-path.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<p>There are two possible tracings that conform to the tracing rule:</p>
<ol type="1">
<li>Start at the academic ability variable and take p1 to the achievement variable.</li>
<li>Start at the academic ability variable and take p2 to the motivation variable, then take p3 to the achievement variable.</li>
</ol>
</div>
</div>
</section>
<section id="example-of-the-tracing-rule-cntd." class="level2">
<h2 class="anchored" data-anchor-id="example-of-the-tracing-rule-cntd.">Example of the Tracing Rule (cntd.)</h2>
<p>Similarly, we could have started at the achievement variable and determined the tracings to get to the academic ability variable:</p>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../img/path-analysis-notes/03-weak-causal-path.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<ol type="1">
<li>Start at the achievement variable and take p1 to the academic ability variable.</li>
<li>Start at the achievement variable and take p3 to the motivation variable, then take p2 to the academic ability variable.</li>
</ol>
</div>
</div>
</section>
<section id="important-note-regarding-the-tracing-rule" class="level2">
<h2 class="anchored" data-anchor-id="important-note-regarding-the-tracing-rule">Important Note Regarding the Tracing Rule</h2>
<p>Note that when we are considering tracings, we do not have to worry about the direction of the arrow, only that there is a path we can trace. The only rule regarding arrowheads is that a variable can not be both entered and exited through an arrowhead.</p>
</section>
<section id="back-to-estimating-the-path-coeffients" class="level2">
<h2 class="anchored" data-anchor-id="back-to-estimating-the-path-coeffients">Back to Estimating the Path Coeffients</h2>
<p>Each tracing yields a product of the path coefficents used in the tracing. Thus the first tracing is <span class="math inline">\(p1\)</span> (there is only one path, so the product is simply the path), and the second tracing yields <span class="math inline">\(p2 \times p3\)</span>. Since the tracing rule says that the correlation between academic ability and achievement is equal to the sum of the products yielded by the tracings, we know that:</p>
<p><span class="math display">\[
\begin{split}
r_{\mathrm{academic~ability,~ achievement}} &amp;= p1 + p2(p3) \\[1em]
.737 &amp;= p1 + p2(p3)
\end{split}
\]</span></p>
</section>
<section id="your-turn" class="level2">
<h2 class="anchored" data-anchor-id="your-turn">Your Turn</h2>
<p>Use the tracing rule to write two more equations. The first equation should represent the correlation between motivation and achievement, and the second equation should represent the correlation between ability and motivation.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../img/path-analysis-notes/03-weak-causal-path.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="check-your-work" class="level2">
<h2 class="anchored" data-anchor-id="check-your-work">Check Your Work</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../img/path-analysis-notes/03-weak-causal-path.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<p>To represent the correlation between motivation and achievement we have two potential tracings:</p>
<ol type="1">
<li>Start at the motivation and take p3 to the achievement variable.</li>
<li>Start at the motivation variable and take p2 to the academic ability variable, then take p1 to the achievement variable.</li>
</ol>
<p><span class="math display">\[
\begin{split}
r_{\mathrm{motivation,~ achievement}} &amp;= p3 + p2(p1) \\[1em]
.255&amp;= p3 + p2(p1)
\end{split}
\]</span></p>
</div>
</div>
</section>
<section id="check-your-work-1" class="level2">
<h2 class="anchored" data-anchor-id="check-your-work-1">Check Your Work</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../img/path-analysis-notes/03-weak-causal-path.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<p>To represent the correlation between academic ability and motivation we have one tracing:</p>
<ol type="1">
<li>Start at the academic ability and take p2 to the motivation variable.</li>
</ol>
<p><span class="math display">\[
\begin{split}
r_{\mathrm{academic~ability,~ motivation}} &amp;= p2 \\[1em]
.205&amp;= p2
\end{split}
\]</span></p>
<p>QUESTION: Why can’t we use the tracing that takes p1 from academic ability to achievement then takes p3 to motivation??</p>
</div>
</div>
</section>
<section id="solving-for-p1-p2-and-p3" class="level2">
<h2 class="anchored" data-anchor-id="solving-for-p1-p2-and-p3">Solving for p1, p2, and p3</h2>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">Equations</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">p1</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false">p3</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-4" role="tab" aria-controls="tabset-1-4" aria-selected="false">Back to p1</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<p>We now have three equations with three unknowns. We can solve this system of equations to find p1, p2, and p3.</p>
<p><span class="math display">\[
\begin{split}
.737 &amp;= p1 + p2(p3) \\[1em]
.255 &amp;= p3 + p2(p1) \\[1em]
.205 &amp;= p2
\end{split}
\]</span></p>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p>Substitute in .205 for p2 in the first equation and solve for p1.</p>
<p><span class="math display">\[
\begin{split}
.737 &amp;= p1 + p2(p3) \\[1em]
.737 &amp;= p1 + .205(p3) \\[1em]
p1 &amp;= .737 - .205(p3)
\end{split}
\]</span></p>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<p>Now substitute .205 in for p2 and <span class="math inline">\(.737 - .205(p3)\)</span> in for p1 in the second equation and solve for p3.</p>
<p><span class="math display">\[
\begin{split}
.255 &amp;= p3 + p2(p1) \\[1em]
.255 &amp;= p3 + .205(.737 - .205(p3)) \\[1em]
.255 &amp;= p3 + 0.151085 - 0.042025(p3) \\[1em]
0.103915 &amp;= 0.957975(p3) \\[1em]
p3 &amp;= .108
\end{split}
\]</span></p>
</div>
<div id="tabset-1-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-4-tab">
<p>Now substitute .205 in for p2 and .108 in for p3 in the first equation and solve for p1.</p>
<p><span class="math display">\[
\begin{split}
.737 &amp;= p1 + p2(p3) \\[1em]
.737 &amp;= p1 + .205(.108) \\[1em]
.737 &amp;= p1 + 0.02214 \\[1em]
p1 &amp;= .715
\end{split}
\]</span></p>
</div>
</div>
</div>
</section>
<section id="path-diagram-with-estimated-path-coefficients" class="level2">
<h2 class="anchored" data-anchor-id="path-diagram-with-estimated-path-coefficients">Path Diagram with Estimated Path Coefficients</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../img/path-analysis-notes/04-estimated-weak-causal-model.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpreting-path-coefficients" class="level2">
<h2 class="anchored" data-anchor-id="interpreting-path-coefficients">Interpreting Path Coefficients</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../img/path-analysis-notes/04-estimated-weak-causal-model.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<p>Path coefficients are <strong>standardized</strong> coefficients which can be interpreted similar to standardized regression coefficients.</p>
<ul>
<li>Given the adequacy of the path model, each 1-standard deviation increase in motivation increases achievement by .108 standard deviations, on average.</li>
<li>Given the adequacy of the path model, each 1-standard deviation increase in academic ability increases achievement by .715 standard deviations, on average.</li>
<li>Given the adequacy of the path model, each 1-standard deviation increase in academic ability increases motivation by .205 standard deviations, on average.</li>
</ul>
</div>
</div>
</section>
<section id="interpreting-path-coefficients-cntd." class="level2">
<h2 class="anchored" data-anchor-id="interpreting-path-coefficients-cntd.">Interpreting Path Coefficients (cntd.)</h2>
<p>There are two things to note when we interpret path coefficients that are different from when we interpret regression coefficients.</p>
<ul>
<li>We include “given the adequacy of the model” in our interpretation. This is important because the values of the path coefficients absolutely depend on the weak causal model specified (i.e., how you draw the path diagram).</li>
<li>Because we are positing a causal relationship, we can use the causal type language in our interpretation. E.g., an increase in <em>X</em> leads to an increase in <em>Y</em>.</li>
</ul>
<p>Note also that the interpretation is not controlling for anything. These are simple relationships that we are interpreting.</p>
</section>
<section id="estimating-path-coefficients-via-regression" class="level2">
<h2 class="anchored" data-anchor-id="estimating-path-coefficients-via-regression">Estimating Path Coefficients via Regression</h2>
<div class="columns">
<p>We can also find the path coefficients using regression rather than algebra. To determine the path coefficients in the weak causal model, we fit a set of regression models using the “causes” as predictors of any particular effect.</p><div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../img/path-analysis-notes/03-weak-causal-path.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<p>In our path diagram there are two effects, so we would need to fit two separate regression models. The syntax for these models would be:</p>
<pre><code>achievement ~ 0 + ability + motivation
motivation ~ 0 + ability</code></pre>
</div>
</div>
</section>
<section id="estimating-path-coefficients-via-regression-cntd." class="level2">
<h2 class="anchored" data-anchor-id="estimating-path-coefficients-via-regression-cntd.">Estimating Path Coefficients via Regression (cntd.)</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Path coefficients for paths to achievement</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(<span class="fu">lm</span>(achievement <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> ability <span class="sc">+</span> motivation, <span class="at">data =</span> sim_dat))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term       estimate std.error statistic   p.value
  &lt;chr&gt;         &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 ability       0.715    0.0216     33.1  8.26e-163
2 motivation    0.108    0.0216      5.02 5.97e-  7</code></pre>
</div>
</div>
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Path coefficient for paths to motivation</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(<span class="fu">lm</span>(motivation <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> ability, <span class="at">data =</span> sim_dat))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  term    estimate std.error statistic  p.value
  &lt;chr&gt;      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 ability    0.205    0.0310      6.62 5.85e-11</code></pre>
</div>
</div>
</section>
<section id="residual-variation" class="level2">
<h2 class="anchored" data-anchor-id="residual-variation">Residual Variation</h2>
<p>Even if the causal relationships were specified correctly, the model likely does not include ALL of the causes for motivation and achievement. There is also unaccounted for variation due to random variation and measurement error. To account for these three sources of variation in the weak causal model, we will add an error term to eavch of the effects in the path model.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../img/path-analysis-notes/05-est-weak-causal-model-errors.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="estimating-residual-variation" class="level2">
<h2 class="anchored" data-anchor-id="estimating-residual-variation">Estimating Residual Variation</h2>
<p>We can also estimate the path coefficients for the error terms. These path coefficients are computed as,</p>
<p><span class="math display">\[
\epsilon_k = \sqrt{1 - R^2_k}
\]</span> where, <span class="math inline">\(R^2_k\)</span> is the <span class="math inline">\(R^2\)</span>-value from the regression model fitted to compute the initial path coefficients.</p>
</section>
<section id="estimating-residual-variation-cntd." class="level2">
<h2 class="anchored" data-anchor-id="estimating-residual-variation-cntd.">Estimating Residual Variation (cntd.)</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Path coefficients for error term on achievement</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(<span class="fu">lm</span>(achievement <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> ability <span class="sc">+</span> motivation, <span class="at">data =</span> sim_dat))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic   p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.554         0.554 0.668      621. 6.36e-176     2 -1014. 2034. 2049.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="dv">1</span> <span class="sc">-</span> .<span class="dv">554</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6678323</code></pre>
</div>
</div>
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Path coefficient for error term on motivation</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(<span class="fu">lm</span>(motivation <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> ability, <span class="at">data =</span> sim_dat))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1    0.0420        0.0411 0.979        NA      NA    NA -1397. 2798. 2808.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="dv">1</span> <span class="sc">-</span> .<span class="dv">0420</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9787747</code></pre>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../img/path-analysis-notes/06-complete-est-weak-causal-model.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="how-do-we-draw-path-diagram" class="level2">
<h2 class="anchored" data-anchor-id="how-do-we-draw-path-diagram">How Do We Draw Path Diagram?</h2>
<ul>
<li>Theory/prior research</li>
<li>Logic/expert understanding/common sense</li>
</ul>
<p>We also need to pay attention to <strong>time precedence</strong>. Cause does not operate backward in time. In our example, academic ability is well-documented as something that does not change after grade school. Thus, it would precede motivation and achievement in time.</p>
</section>
<section id="a-little-more-about-cause" class="level2">
<h2 class="anchored" data-anchor-id="a-little-more-about-cause">A Little More About Cause</h2>
<p>What do we mean when we say “<em>X</em> causes <em>Y</em>”? Contrary to popular belief, we do not mean that changing <em>X</em> has a direct, and immediate change on <em>Y</em>. For example, it is now well known that smoking causes lung cancer.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../img/path-analysis-notes/09-smoking-cancer.png" class="img-fluid figure-img" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
<p>But, not everyone who smokes ends up getting lung cancer.</p>
</section>
<section id="a-little-more-about-cause-cntd." class="level2">
<h2 class="anchored" data-anchor-id="a-little-more-about-cause-cntd.">A Little More About Cause (cntd.)</h2>
<p>Instead, cause is a probabilistic statement about the world. When we say smoking causes lung cancer what we mean, statistically, is that smoking increases the probability of developing lung cancer.</p>
<p><br></p>
<p>Moreover, this increased probability is due to smoking, and not something else.</p>
</section>
<section id="requirements-for-cause" class="level2">
<h2 class="anchored" data-anchor-id="requirements-for-cause">Requirements for Cause</h2>
<p>There are three primary requirements for a causal relationship between <em>X</em> and <em>Y</em>.</p>
<ol type="1">
<li>There must be a relationship between <em>X</em> and <em>Y</em>. (Correlation is a necessary component of causation.)</li>
<li>Time precedence (Causes must occur prior to effects.)</li>
<li>Relationship must not be spurious.</li>
</ol>
</section>
<section id="including-time-precedence-in-the-path-diagram" class="level2">
<h2 class="anchored" data-anchor-id="including-time-precedence-in-the-path-diagram">Including Time Precedence in the Path Diagram</h2>
<p>Time precedence is often reflected in the orientation of the model. Variables that occur earlier in time are oriented further to the left side of the diagram than variables that occur later.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../img/path-analysis-notes/09-smoking-cancer.png" class="img-fluid figure-img" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
<p>In the smoking example, to be considered the cause for lung cancer, smoking has to occur prior to the onset of lung cancer.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
</section>
<section id="including-time-precedence-in-the-path-diagram-cntd." class="level2">
<h2 class="anchored" data-anchor-id="including-time-precedence-in-the-path-diagram-cntd.">Including Time Precedence in the Path Diagram (cntd.)</h2>
<p>In our path diagram relating academic ability and motivation to acheivement, academic ability is furthest to the left (it occurs earliest), followed by motivation, and then academic achievement.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../img/path-analysis-notes/06-complete-est-weak-causal-model.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="common-cause" class="level2">
<h2 class="anchored" data-anchor-id="common-cause">Common Cause</h2>
<p>A common cause is a variable that is a cause of both <em>X</em> and <em>Y</em> which accounts for the relationship between <em>X</em> and <em>Y</em>. Consider the following example where we want to look at the causal impact of participation in Head Start programs on academic achievement.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../img/path-analysis-notes/07-head-start-achievment.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>In practice, the path coefficient tends to be negative. That is Head Start participants tend to have lower academic achievement than their non-Head Start peers.</p>
</section>
<section id="common-cause-cntd." class="level2">
<h2 class="anchored" data-anchor-id="common-cause-cntd.">Common Cause (cntd.)</h2>
<p>A common cause of both Head Start participation and academic achievement is poverty. This is shown below.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../img/path-analysis-notes/08-head-start-achievment-poverty.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>Once we include poverty as a common cause, the path coefficient between Head Start participation and academic achievement switches direction. That is, after including poverty in the path model, Head Start participants tend to have higher academic achievement than their non-Head Start peers. This is akin to how effects in a regression model might change after we control for other predictors.</p>
</section>
<section id="common-cause-cntd.-1" class="level2">
<h2 class="anchored" data-anchor-id="common-cause-cntd.-1">Common Cause (cntd.)</h2>
<p>In order to meet the third causal requirement, we need to include ALL common causes in the model. This requirement is the hardest to prove.</p>
</section>
<section id="non-recursive-models" class="level2">
<h2 class="anchored" data-anchor-id="non-recursive-models">Non-Recursive Models</h2>
<p>In the path diagrams we have looked at so far, the causal paths have gone in only one direction; there is a distinct cause and effect. The error terms on the effect variables are also all uncorrelated. These are called <em>recursive models</em>. It is possible for variables to effect each other (e.g., predator–prey relationships), or for the error terms to be correlated. This is called a <em>non-recursive model</em>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../img/path-analysis-notes/11-nonrecursive-model.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="under-identified-models" class="level2">
<h2 class="anchored" data-anchor-id="under-identified-models">Under-Identified Models</h2>
<p>The problem with estimating the path coefficients in the non-recursive model is it is under-identified. In our predator–prey model, we need to estimate four path coefficients, but only have three correlations (equations) from which to do so. We can’t solve this without adding additional constraints!</p>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../img/path-analysis-notes/12-nonrecursive-model-paths.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<p><span class="math display">\[
\begin{split}
r_{\mathrm{H,W}} &amp;= p1 + p2(p4) \\[1em]
r_{\mathrm{H,R}} &amp;= p2 + p1(p3) \\[1em]
r_{\mathrm{H,W}} &amp;= p3 + p4 + p1(p2)
\end{split}
\]</span></p>
</div>
</div>
</section>
<section id="over-identified-models" class="level2">
<h2 class="anchored" data-anchor-id="over-identified-models">Over-Identified Models</h2>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Note that the top–bottom orientation typically doesn’t mean anything—it is just used for aesthetics in the layout.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->

<script>
  // htmlwidgets need to know to resize themselves when slides are shown/hidden.
  // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
  // slide changes (different for each slide format).
  (function () {
    // dispatch for htmlwidgets
    function fireSlideEnter() {
      const event = window.document.createEvent("Event");
      event.initEvent("slideenter", true, true);
      window.document.dispatchEvent(event);
    }

    function fireSlideChanged(previousSlide, currentSlide) {
      fireSlideEnter();

      // dispatch for shiny
      if (window.jQuery) {
        if (previousSlide) {
          window.jQuery(previousSlide).trigger("hidden");
        }
        if (currentSlide) {
          window.jQuery(currentSlide).trigger("shown");
        }
      }
    }

    // hookup for slidy
    if (window.w3c_slidy) {
      window.w3c_slidy.add_observer(function (slide_num) {
        // slide_num starts at position 1
        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
      });
    }

  })();
</script>

<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>