<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2022-10-13">

<title>EPsy 8264 - 🎶 Regression from Summary Measures</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<script src="../site_libs/kePrint/kePrint.js"></script>
<link href="../site_libs/lightable/lightable.css" rel="stylesheet">
<link href="../site_libs/pagedtable/css/pagedtable.css" rel="stylesheet">
<script src="../site_libs/pagedtable/js/pagedtable.js"></script>
<script src="https://kit.fontawesome.com/e5da75ca36.js" crossorigin="anonymous"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../assets/sticky-notes.css">
<link rel="stylesheet" href="../assets/style.css">
<link rel="stylesheet" href="../assets/notes.css">
<link rel="stylesheet" href="../assets/gt-table-styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">EPsy 8264</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../schedule.html" rel="" target="">
 <span class="menu-text">Schedule</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../assignments.html" rel="" target="">
 <span class="menu-text">Assignments</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../data.html" rel="" target="">
 <span class="menu-text">Data</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">Instructor &amp; TA</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../mission-statements.html" rel="" target="">
 <span class="menu-text">Mission Statements</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../umn-policies.html" rel="" target="">
 <span class="menu-text">University Policies</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#computing-regression-coefficients-from-summary-data" id="toc-computing-regression-coefficients-from-summary-data" class="nav-link active" data-scroll-target="#computing-regression-coefficients-from-summary-data">Computing Regression Coefficients from Summary Data</a>
  <ul class="collapse">
  <li><a href="#going-from-the-correlations-to-covariances" id="toc-going-from-the-correlations-to-covariances" class="nav-link" data-scroll-target="#going-from-the-correlations-to-covariances">Going From the Correlations to Covariances</a></li>
  <li><a href="#finding-the-predictor-coefficients" id="toc-finding-the-predictor-coefficients" class="nav-link" data-scroll-target="#finding-the-predictor-coefficients">Finding the Predictor Coefficients</a></li>
  <li><a href="#computing-the-intercept" id="toc-computing-the-intercept" class="nav-link" data-scroll-target="#computing-the-intercept">Computing the Intercept</a></li>
  </ul></li>
  <li><a href="#standard-errors-for-the-coefficients" id="toc-standard-errors-for-the-coefficients" class="nav-link" data-scroll-target="#standard-errors-for-the-coefficients">Standard Errors for the Coefficients</a>
  <ul class="collapse">
  <li><a href="#compute-mathbfxintercalmathbfx-matrix" id="toc-compute-mathbfxintercalmathbfx-matrix" class="nav-link" data-scroll-target="#compute-mathbfxintercalmathbfx-matrix">Compute <span class="math inline">\(\mathbf{X}^\intercal\mathbf{X}\)</span> Matrix</a></li>
  </ul></li>
  <li><a href="#standardized-regression-from-summaries" id="toc-standardized-regression-from-summaries" class="nav-link" data-scroll-target="#standardized-regression-from-summaries">Standardized Regression from Summaries</a></li>
  <li><a href="#simulating-data-using-summary-values" id="toc-simulating-data-using-summary-values" class="nav-link" data-scroll-target="#simulating-data-using-summary-values">Simulating Data Using Summary Values</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">🎶 Regression from Summary Measures</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 13, 2022</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<hr>
<p>When we have raw data, we can fit a regression model using the <code>lm()</code> function and obtain model- and coefficient-level summaries using the <code>glance()</code> and <code>tidy()</code> functions respectively. However, there are times we might want to compute regression coefficients and standard errors, but are not given the raw data. This is common for example in articles, which often report summaries rather than providing raw data. In this set of notes, we will examine how we can fit a regression model to summaries of the data, rather than to the raw data itself.</p>
<!-- - [[CSV]](https://raw.githubusercontent.com/zief0002/pensive-giraffe/main/data/states-2019.csv) -->
<ul>
<li><a href="https://raw.githubusercontent.com/zief0002/redesigned-adventure/main/scripts/15-regression-from-summary-measures.R">[R Script File]</a>.R)</li>
</ul>
<p>So long as we have certain statistical information we can compute the regression coefficients and standard errors without having the raw data. To do this, we need the sample size, means, standard deviations, and correlations between variables. For example, consider the following summary table:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="lightable-classic table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Correlation matrix for five attributes measured on <em>n</em> = 1,000 students. Means (standard deviations) for each attribute are provided on the main diagonal. </caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Measure</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">1.</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">2.</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">3.</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">4.</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">5.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1. Achievement</td>
<td style="text-align: center;">50 (10)</td>
<td style="text-align: center;">---</td>
<td style="text-align: center;">---</td>
<td style="text-align: center;">---</td>
<td style="text-align: center;">---</td>
</tr>
<tr class="even">
<td style="text-align: left;">2. Ability</td>
<td style="text-align: center;">0.737</td>
<td style="text-align: center;">100 (15)</td>
<td style="text-align: center;">---</td>
<td style="text-align: center;">---</td>
<td style="text-align: center;">---</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3. Motivation</td>
<td style="text-align: center;">0.255</td>
<td style="text-align: center;">0.205</td>
<td style="text-align: center;">50 (10)</td>
<td style="text-align: center;">---</td>
<td style="text-align: center;">---</td>
</tr>
<tr class="even">
<td style="text-align: left;">4. Previous Coursework</td>
<td style="text-align: center;">0.615</td>
<td style="text-align: center;">0.498</td>
<td style="text-align: center;">0.375</td>
<td style="text-align: center;">4 (2)</td>
<td style="text-align: center;">---</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5. Family Background</td>
<td style="text-align: center;">0.417</td>
<td style="text-align: center;">0.417</td>
<td style="text-align: center;">0.190</td>
<td style="text-align: center;">0.372</td>
<td style="text-align: center;">0 (1)</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Say we wanted to use this information to fit a regression model to predict variation in achievement using the other four predictors. Mathematically,</p>
<p><span class="math display">\[
\begin{split}
\mathrm{Achievement}_i = &amp;\beta_0 + \beta_1(\mathrm{Ability}_i) + \beta_2(\mathrm{Motivation}_i) + \\
&amp;\beta_3(\mathrm{Coursework~}_i) + \beta_4(\mathrm{Family~Background}_i) + \epsilon_i
\end{split}
\]</span></p>
<p>To do this we are going to create the correlation matrix, the vector of attribute means, and the vector of attribute standard deviations.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create correlation matrix</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>corrs <span class="ot">=</span> <span class="fu">matrix</span>(</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> <span class="fu">c</span>(</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    <span class="fl">1.000</span>, <span class="fl">0.737</span>, <span class="fl">0.255</span>, <span class="fl">0.615</span>, <span class="fl">0.417</span>,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.737</span>, <span class="fl">1.000</span>, <span class="fl">0.205</span>, <span class="fl">0.498</span>, <span class="fl">0.417</span>,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.255</span>, <span class="fl">0.205</span>, <span class="fl">1.000</span>, <span class="fl">0.375</span>, <span class="fl">0.190</span>,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.615</span>, <span class="fl">0.498</span>, <span class="fl">0.375</span>, <span class="fl">1.000</span>, <span class="fl">0.372</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.417</span>, <span class="fl">0.417</span>, <span class="fl">0.190</span>, <span class="fl">0.372</span>, <span class="fl">1.000</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">nrow =</span> <span class="dv">5</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># View correlation matrix</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>corrs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      [,1]  [,2]  [,3]  [,4]  [,5]
[1,] 1.000 0.737 0.255 0.615 0.417
[2,] 0.737 1.000 0.205 0.498 0.417
[3,] 0.255 0.205 1.000 0.375 0.190
[4,] 0.615 0.498 0.375 1.000 0.372
[5,] 0.417 0.417 0.190 0.372 1.000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create mean vector</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>means <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">100</span>, <span class="dv">50</span>, <span class="dv">4</span>, <span class="dv">0</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create sd vector</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>sds <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">15</span>, <span class="dv">10</span>, <span class="dv">2</span>, <span class="dv">1</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Set sample size</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">1000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br></p>
<section id="computing-regression-coefficients-from-summary-data" class="level1">
<h1>Computing Regression Coefficients from Summary Data</h1>
<p>To compute the coefficients from raw data, recall that we solve the normal equations based on:</p>
<p><span class="math display">\[
\mathbf{X}^\intercal\mathbf{Xb} = \mathbf{X}^\intercal\mathbf{y}
\]</span></p>
<p>Recall that if we mean center the variables in a regression analysis, the coefficients for this set of predictors would be exactly the same as if we used the raw predictors. (The intercept would differ, but ignore that for now.) That is if we solved the normal equations based on</p>
<p><span class="math display">\[
\mathbf{X}_{\mathrm{Dev}}^\intercal\mathbf{X}_{\mathrm{Dev}}\mathbf{b} = \mathbf{X}_{\mathrm{Dev}}^\intercal\mathbf{y}_{\mathrm{Dev}}
\]</span></p>
<p>the elements of <strong>b</strong> associated with the predictors in this set of equations would be the same as those from solving for <strong>b</strong> in <span class="math inline">\(\mathbf{X}^\intercal\mathbf{Xb} = \mathbf{X}^\intercal\mathbf{y}\)</span>.</p>
<p>So, if our goal is to find the coefficients associated with the predictors, it doesn’t matter if we use the raw or mean centered predictors. This is useful since there is a direct relationship between the <span class="math inline">\(\mathbf{X}_{\mathrm{Dev}}^\intercal\mathbf{X}_{\mathrm{Dev}}\)</span> matrix and the variance-covariance matrix of the raw predictors:</p>
<p><span class="math display">\[
\mathrm{Cov}(X,X) = \frac{\mathbf{X}_{\mathrm{Dev}}^\intercal\mathbf{X}_{\mathrm{Dev}}}{n-1}
\]</span></p>
<p>Similarly, there is a direct relationship between the <span class="math inline">\(\mathbf{X}_{\mathrm{Dev}}^\intercal\mathbf{y}_{\mathrm{Dev}}\)</span> matrix and the vector of covariances between the raw predictors and the raw outcome:</p>
<p><span class="math display">\[
\mathrm{Cov}(X,y) = \frac{\mathbf{X}_{\mathrm{Dev}}^\intercal\mathbf{y}_{\mathrm{Dev}}}{n-1}
\]</span></p>
<p>This means we can write our second set of normal equations (using the mean centered variables) as:</p>
<p><span class="math display">\[
\begin{split}
\mathbf{X}_{\mathrm{Dev}}^\intercal\mathbf{X}_{\mathrm{Dev}}\mathbf{b} &amp;= \mathbf{X}_{\mathrm{Dev}}^\intercal\mathbf{y}_{\mathrm{Dev}} \\[1em]
\mathrm{Cov}(X,X) (n-1)\mathbf{b} &amp;= \mathrm{Cov}(X,y)(n-1) \\[1em]
\mathrm{Cov}(X,X) \mathbf{b} &amp;= \mathrm{Cov}(X,y)
\end{split}
\]</span></p>
<p>Which we can use to solve for <strong>b</strong>:</p>
<p><span class="math display">\[
\mathbf{b} = \mathrm{Cov}(X,X)^{-1}\mathrm{Cov}(X,y)
\]</span></p>
<p><br></p>
<section id="going-from-the-correlations-to-covariances" class="level2">
<h2 class="anchored" data-anchor-id="going-from-the-correlations-to-covariances">Going From the Correlations to Covariances</h2>
<p>The summary measures we have give correlations, not covariances. However, it is quite easy to convert a correlation matrix to a covariance matrix. From the chapter <a href="https://zief0002.github.io/matrix-algebra/statistical-application-sscp-variancecovariance-and-correlation-matrices.html">Statistical Application: SSCP, Variance–Covariance, and Correlation Matrices</a> in <em>Matrix Algebra for Educational Scientists</em>, know that:</p>
<p><span class="math display">\[
\mathbf{R} = \mathbf{S} \boldsymbol\Sigma \mathbf{S}
\]</span></p>
<p>where <strong>R</strong> is the correlation matrix, <span class="math inline">\(\boldsymbol\Sigma\)</span> is the covariance matrix, and <strong>S</strong> is a diagonal scaling matrix with diagonal elements equal to the reciprocal of the standard deviations of each of the variables in the covariance matrix. Re-arranging this:</p>
<p><span class="math display">\[
\boldsymbol\Sigma = \mathbf{S}^{-1} \mathbf{R} \mathbf{S}^{-1}
\]</span></p>
<p>Recall that the inverse of a diagonal matrix is another diagonal matrix where the diagonal elements are the resciprocals of the original. Thus the diagonal elements of the inverse of our scaling matrix will be the standard deviations of the variables. Using this formula, we can now convert the given correlation matrix to a covariance matrix.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the scaling matrix S^(-1)</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>S_inv <span class="ot">=</span> <span class="fu">diag</span>(sds)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>S_inv</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2] [,3] [,4] [,5]
[1,]   10    0    0    0    0
[2,]    0   15    0    0    0
[3,]    0    0   10    0    0
[4,]    0    0    0    2    0
[5,]    0    0    0    0    1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute covariance matrix</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>covs <span class="ot">=</span> S_inv <span class="sc">%*%</span> corrs <span class="sc">%*%</span> S_inv</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>covs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       [,1]    [,2]   [,3]   [,4]  [,5]
[1,] 100.00 110.550  25.50 12.300 4.170
[2,] 110.55 225.000  30.75 14.940 6.255
[3,]  25.50  30.750 100.00  7.500 1.900
[4,]  12.30  14.940   7.50  4.000 0.744
[5,]   4.17   6.255   1.90  0.744 1.000</code></pre>
</div>
</div>
<p>Adding in the row and column names:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="lightable-classic table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Variance-covariance matrix for five attributes measured on <em>n</em> = 1,000 students. </caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Achievement</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Ability</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Motivation</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Previous.Coursework</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Family.Background</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Achievement</td>
<td style="text-align: left;">100.00</td>
<td style="text-align: center;">110.550</td>
<td style="text-align: center;">25.50</td>
<td style="text-align: center;">12.300</td>
<td style="text-align: center;">4.170</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ability</td>
<td style="text-align: left;">110.55</td>
<td style="text-align: center;">225.000</td>
<td style="text-align: center;">30.75</td>
<td style="text-align: center;">14.940</td>
<td style="text-align: center;">6.255</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Motivation</td>
<td style="text-align: left;">25.50</td>
<td style="text-align: center;">30.750</td>
<td style="text-align: center;">100.00</td>
<td style="text-align: center;">7.500</td>
<td style="text-align: center;">1.900</td>
</tr>
<tr class="even">
<td style="text-align: left;">Previous Coursework</td>
<td style="text-align: left;">12.30</td>
<td style="text-align: center;">14.940</td>
<td style="text-align: center;">7.50</td>
<td style="text-align: center;">4.000</td>
<td style="text-align: center;">0.744</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Family Background</td>
<td style="text-align: left;">4.17</td>
<td style="text-align: center;">6.255</td>
<td style="text-align: center;">1.90</td>
<td style="text-align: center;">0.744</td>
<td style="text-align: center;">1.000</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><br></p>
<p>Remember, the diagonal elements in the covariance matrix are variances of each variable and the off-diagonal elements are the covariances between two variables. For example, the first diagonal element is 100, which is the variance of the achievement variable. The remaining elements in the first column indicate the covariances between achievement and ability, achievement and motivation, achievement and previous coursework, and achievement and family background.</p>
<p><br></p>
</section>
<section id="finding-the-predictor-coefficients" class="level2">
<h2 class="anchored" data-anchor-id="finding-the-predictor-coefficients">Finding the Predictor Coefficients</h2>
<p>To compute the coefficients for the predictors, we need to obtain two things:</p>
<ul>
<li>Cov(X, X): The variance-covariance matrix of the predictors, and</li>
<li>Cov(X, y): The vector that contains the covariances between the outcome and each predictor. (Note: This vector does not include the variance of the outcome, only the covariances with the predictors.)</li>
</ul>
<p>In our example, the elements in the first column (or row) of the variance-covariance matrix <em>other than the variance of the outcome</em> are the values in the vector Cov(X, y). The elements in the other rows/columns make up the elements of the Cov(X, X) matrix.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="lightable-classic table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Variance-covariance matrix for five attributes measured on n = 1,000 students. </caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Achievement</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Ability</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Motivation</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Previous.Coursework</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Family.Background</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; color: #222222 !important;">Achievement</td>
<td style="text-align: left; color: #0072b2 !important; color: #222222 !important;">100.00</td>
<td style="text-align: center; color: #cc79a7 !important; color: #222222 !important;">110.550</td>
<td style="text-align: center; color: #cc79a7 !important; color: #222222 !important;">25.50</td>
<td style="text-align: center; color: #cc79a7 !important; color: #222222 !important;">12.300</td>
<td style="text-align: center; color: #cc79a7 !important; color: #222222 !important;">4.170</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ability</td>
<td style="text-align: left; color: #0072b2 !important;">110.55</td>
<td style="text-align: center; color: #cc79a7 !important;">225.000</td>
<td style="text-align: center; color: #cc79a7 !important;">30.75</td>
<td style="text-align: center; color: #cc79a7 !important;">14.940</td>
<td style="text-align: center; color: #cc79a7 !important;">6.255</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Motivation</td>
<td style="text-align: left; color: #0072b2 !important;">25.50</td>
<td style="text-align: center; color: #cc79a7 !important;">30.750</td>
<td style="text-align: center; color: #cc79a7 !important;">100.00</td>
<td style="text-align: center; color: #cc79a7 !important;">7.500</td>
<td style="text-align: center; color: #cc79a7 !important;">1.900</td>
</tr>
<tr class="even">
<td style="text-align: left;">Previous Coursework</td>
<td style="text-align: left; color: #0072b2 !important;">12.30</td>
<td style="text-align: center; color: #cc79a7 !important;">14.940</td>
<td style="text-align: center; color: #cc79a7 !important;">7.50</td>
<td style="text-align: center; color: #cc79a7 !important;">4.000</td>
<td style="text-align: center; color: #cc79a7 !important;">0.744</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Family Background</td>
<td style="text-align: left; color: #0072b2 !important;">4.17</td>
<td style="text-align: center; color: #cc79a7 !important;">6.255</td>
<td style="text-align: center; color: #cc79a7 !important;">1.90</td>
<td style="text-align: center; color: #cc79a7 !important;">0.744</td>
<td style="text-align: center; color: #cc79a7 !important;">1.000</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><br></p>
<p>Here the blue elements compose Cov(X, y) and the reddish-purple elements constitute Cov(X, X). We can create this vector and matrix using indexing.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create Cov(X, y)</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>cov_xy <span class="ot">=</span> covs[<span class="sc">-</span><span class="dv">1</span> , <span class="dv">1</span>]</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>cov_xy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 110.55  25.50  12.30   4.17</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create Cov(X, X)</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>cov_xx <span class="ot">=</span> covs[<span class="sc">-</span><span class="dv">1</span> , <span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>cov_xx</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        [,1]   [,2]   [,3]  [,4]
[1,] 225.000  30.75 14.940 6.255
[2,]  30.750 100.00  7.500 1.900
[3,]  14.940   7.50  4.000 0.744
[4,]   6.255   1.90  0.744 1.000</code></pre>
</div>
</div>
<p>Then we can use these to compute the predictor coefficients.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute predictor coefficients</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>b <span class="ot">=</span> <span class="fu">solve</span>(cov_xx) <span class="sc">%*%</span> cov_xy</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>b</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           [,1]
[1,] 0.36737330
[2,] 0.01257721
[3,] 1.55001342
[4,] 0.69497334</code></pre>
</div>
</div>
<p>Thus the coefficient estimates are:</p>
<ul>
<li><span class="math inline">\(\hat\beta_{\mathrm{Ability}} = 0.367\)</span></li>
<li><span class="math inline">\(\hat\beta_{\mathrm{Motivation}} = 0.013\)</span></li>
<li><span class="math inline">\(\hat\beta_{\mathrm{Previous~Coursework}} = 1.550\)</span></li>
<li><span class="math inline">\(\hat\beta_{\mathrm{Family~Background}} = 0.695\)</span></li>
</ul>
<p><br></p>
</section>
<section id="computing-the-intercept" class="level2">
<h2 class="anchored" data-anchor-id="computing-the-intercept">Computing the Intercept</h2>
<p>To compute the intercept, we can use the following:</p>
<p><span class="math display">\[
\hat\beta_0 = \bar{y} - \bar{\mathbf{x}}^\intercal\mathbf{b}
\]</span></p>
<p>where <span class="math inline">\(\bar{y}\)</span> is the mean of the outcome, <span class="math inline">\(\bar{\mathbf{x}}\)</span> is the vector of predictor means, and <strong>b</strong> is the associated vector of predictor coefficients.</p>
<p>In our example,</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute intercept</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>b_0 <span class="ot">=</span> means[<span class="dv">1</span>] <span class="sc">-</span> <span class="fu">t</span>(means[<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>]) <span class="sc">%*%</span> b</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>b_0</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         [,1]
[1,] 6.433756</code></pre>
</div>
</div>
<p>Thus the fitted equation for the unstandardized model is:</p>
<p><span class="math display">\[
\begin{split}
\widehat{\mathrm{Achievement}_i} = &amp;6.434 + 0.367(\mathrm{Ability}_i) + 0.013(\mathrm{Motivation}_i) + \\
&amp;1.550(\mathrm{Coursework~}_i) + 0.695(\mathrm{Family~Background}_i)
\end{split}
\]</span></p>
<p><br></p>
</section>
</section>
<section id="standard-errors-for-the-coefficients" class="level1">
<h1>Standard Errors for the Coefficients</h1>
<p>Using the raw data, we estimated the standard error for the coefficients by taking the square root of the diagonal elements of the variance-covariance matrix of the coefficients, where the the variance-covariance matrix of the coefficients was computed as:</p>
<p><span class="math display">\[
\hat\sigma^2_{e} (\mathbf{X}^\intercal\mathbf{X})^{-1}
\]</span></p>
<p>We can use the summary values we have to also obtain the <span class="math inline">\(\hat\sigma^2_{e}\)</span> estimate and to compute the elements of the <span class="math inline">\(\mathbf{X}^\intercal\mathbf{X}\)</span> matrix.</p>
<p><br></p>
<p>The estimate of the residual variance is found using:</p>
<p><span class="math display">\[
\hat\sigma^2_{e} = \hat\sigma^2_y (1 - R^2_{\mathrm{Adj}})
\]</span></p>
<p>where <span class="math inline">\(\hat\sigma^2_y\)</span> is the variance of the outcome and <span class="math inline">\(R^2_{\mathrm{Adj}}\)</span> is the Adjusted <span class="math inline">\(R^2\)</span> value which is found using:</p>
<p><span class="math display">\[
R^2_{\mathrm{Adj}} = 1 - \frac{\mathrm{df}_{\mathrm{Total}}}{\mathrm{df}_{\mathrm{Residual}}}(1 -R^2)
\]</span></p>
<p>To find the <span class="math inline">\(R^2\)</span> value, we can invert the correlation matrix and compute one minus the reciprocal of the diagonal elements of this inverted matrix. The results are the <span class="math inline">\(R^2\)</span> values for the given term as an outcome variable and all other terms in the correlation matrix as predictors.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Invert correlation matrix</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>corr_inv <span class="ot">=</span> <span class="fu">solve</span>(corrs)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the R2 values</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>r2 <span class="ot">=</span> <span class="dv">1</span> <span class="sc">-</span> <span class="dv">1</span><span class="sc">/</span><span class="fu">diag</span>(corr_inv)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>r2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6289704 0.5591756 0.1439290 0.4421816 0.2201437</code></pre>
</div>
</div>
<p>Here the <span class="math inline">\(R^2\)</span> value from regressing achievement on all the other variables in the correlation matrix (e.g., ability, motivation, previous coursework, and family background) is 0.629. We can then use this to compute adjusted <span class="math inline">\(R^2\)</span> and subsequently use that to compute <span class="math inline">\(\hat\sigma^2_y\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute adjusted R2</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>r2_adj <span class="ot">=</span> <span class="dv">1</span> <span class="sc">-</span> (<span class="dv">999</span> <span class="sc">/</span> <span class="dv">995</span>) <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> r2[<span class="dv">1</span>])</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>r2_adj</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6274788</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute estimated residual variance</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>s2_e <span class="ot">=</span> sds[<span class="dv">1</span>]<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> r2_adj)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>s2_e</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 37.25212</code></pre>
</div>
</div>
<p>Our estimate for <span class="math inline">\(\hat\sigma^2_y\)</span> is 37.25.</p>
<p><br></p>
<section id="compute-mathbfxintercalmathbfx-matrix" class="level2">
<h2 class="anchored" data-anchor-id="compute-mathbfxintercalmathbfx-matrix">Compute <span class="math inline">\(\mathbf{X}^\intercal\mathbf{X}\)</span> Matrix</h2>
<p>The elements in the first row and column of the <span class="math inline">\(\mathbf{X}^\intercal\mathbf{X}\)</span> matrix are functions of the sample size and means of the predictor variables. Namely the first element in the first row and column is <em>n</em> and the remaining elements in the that row and column are created as <span class="math inline">\(n\mathbf{M_x}\)</span>, where <em>n</em> is the sample size, and <span class="math inline">\(\mathbf{M_x}\)</span> is the vector of predictor means. The remaining elements constitute a submatrix defined as:</p>
<p><span class="math display">\[
(\mathbf{X}^\intercal\mathbf{X})_{\mathrm{Sub}} = (n-1)\mathrm{Cov}(X,X) + n(\mathbf{M_x})(\mathbf{M_x}^\intercal)
\]</span></p>
<p>where <em>n</em> is the sample size, Cov(X,X) is the variance covariance matrix ofthe predictors, and <span class="math inline">\(\mathbf{M_x}\)</span> is again the vector of predictor means. We cn then create the <span class="math inline">\(\mathbf{X}^\intercal\mathbf{X}\)</span> matrix as:</p>
<p><span class="math display">\[
\require{color}
\begin{split}
\mathbf{X}^\intercal\mathbf{X} &amp;= \begin{bmatrix}{\color[rgb]{0.044147,0.363972,0.636955}n} &amp; {\color[rgb]{0.044147,0.363972,0.636955}n\mathbf{M_x}}\\{\color[rgb]{0.044147,0.363972,0.636955}n\mathbf{M_x}} &amp; {\color[rgb]{0.748052,0.381230,0.589698}(\mathbf{X}^\intercal\mathbf{X})_{\mathrm{Sub}}}\end{bmatrix}
\\[2ex]
&amp;= \begin{bmatrix}{\color[rgb]{0.044147,0.363972,0.636955}n} &amp; {\color[rgb]{0.044147,0.363972,0.636955}n\overline{X1}} &amp; {\color[rgb]{0.044147,0.363972,0.636955}n\overline{X2}} &amp;  {\color[rgb]{0.044147,0.363972,0.636955}n\overline{X3}} &amp; {\color[rgb]{0.044147,0.363972,0.636955}\ldots} &amp; {\color[rgb]{0.044147,0.363972,0.636955}n\overline{Xk}}\\ {\color[rgb]{0.044147,0.363972,0.636955}n\overline{X1}} &amp; &amp; &amp; &amp; &amp;  \\ {\color[rgb]{0.044147,0.363972,0.636955}n\overline{X2}} &amp; &amp; &amp; &amp; &amp;  \\ {\color[rgb]{0.044147,0.363972,0.636955}n\overline{X3}} &amp; &amp; &amp; {\color[rgb]{0.748052,0.381230,0.589698}(\mathbf{X}^\intercal\mathbf{X})_{\mathrm{Sub}}} &amp; &amp;  \\ {\color[rgb]{0.044147,0.363972,0.636955}\vdots} &amp; &amp; &amp; &amp; &amp;  \\ {\color[rgb]{0.044147,0.363972,0.636955}n\overline{Xk}} &amp; &amp; &amp; &amp; &amp;   \end{bmatrix}
\end{split}
\]</span></p>
<p>To create this matrix using R, we will:</p>
<ol type="1">
<li>Compute the submatrix <span class="math inline">\((\mathbf{X}^\intercal\mathbf{X})_{\mathrm{Sub}}\)</span>.</li>
<li>Bind the <span class="math inline">\(n\mathbf{M_x}\)</span> vector to the top of the submatrix.</li>
<li>Bind the vector that contains <em>n</em> and <span class="math inline">\(n\mathbf{M_x}\)</span> to the left of the resulting matrix from Step 2.</li>
</ol>
<p>The resulting matrix is the <span class="math inline">\(\mathbf{X}^\intercal\mathbf{X}\)</span> matrix. For our example,</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Create submatrix</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>sub_mat <span class="ot">=</span> <span class="dv">999</span> <span class="sc">*</span> cov_xx <span class="sc">+</span> <span class="dv">1000</span> <span class="sc">*</span> means[<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>] <span class="sc">%*%</span> <span class="fu">t</span>(means[<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>])</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>sub_mat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             [,1]      [,2]       [,3]     [,4]
[1,] 10224775.000 5030719.2 414925.060 6248.745
[2,]  5030719.250 2599900.0 207492.500 1898.100
[3,]   414925.060  207492.5  19996.000  743.256
[4,]     6248.745    1898.1    743.256  999.000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Bind n(M_x) to top of submatrix</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>mat_2 <span class="ot">=</span> <span class="fu">rbind</span>(<span class="dv">1000</span> <span class="sc">*</span> means[<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>], sub_mat)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>mat_2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             [,1]      [,2]       [,3]     [,4]
[1,]   100000.000   50000.0   4000.000    0.000
[2,] 10224775.000 5030719.2 414925.060 6248.745
[3,]  5030719.250 2599900.0 207492.500 1898.100
[4,]   414925.060  207492.5  19996.000  743.256
[5,]     6248.745    1898.1    743.256  999.000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Bind vector to left of Step 2 matrix</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>XtX <span class="ot">=</span> <span class="fu">cbind</span>(<span class="fu">c</span>(<span class="dv">1000</span>, <span class="dv">1000</span> <span class="sc">*</span> means[<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>]), mat_2)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>XtX</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       [,1]         [,2]      [,3]       [,4]     [,5]
[1,]   1000   100000.000   50000.0   4000.000    0.000
[2,] 100000 10224775.000 5030719.2 414925.060 6248.745
[3,]  50000  5030719.250 2599900.0 207492.500 1898.100
[4,]   4000   414925.060  207492.5  19996.000  743.256
[5,]      0     6248.745    1898.1    743.256  999.000</code></pre>
</div>
</div>
<p>We can then scale this matrix using our previous estimate of the residual variance to obtain the variance-covariance matrix for the coefficients and compute the coefficient standard errors.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute var-cov matrix of b</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>cov_b <span class="ot">=</span> s2_e <span class="sc">*</span> <span class="fu">solve</span>(XtX)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>cov_b</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            [,1]            [,2]            [,3]         [,4]          [,5]
[1,]  2.86183238 -0.021078176856 -0.018522600965  0.052341868  0.1280945885
[2,] -0.02107818  0.000240314903 -0.000001964506 -0.000713772 -0.0009683908
[3,] -0.01852260 -0.000001964506  0.000435428791 -0.000763097 -0.0002472826
[4,]  0.05234187 -0.000713772031 -0.000763096999  0.014297546 -0.0047228461
[5,]  0.12809459 -0.000968390764 -0.000247282552 -0.004722846  0.0473303248</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute SEs</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>se <span class="ot">=</span> <span class="fu">sqrt</span>(<span class="fu">diag</span>(cov_b))</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>se</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.69169512 0.01550209 0.02086693 0.11957235 0.21755534</code></pre>
</div>
</div>
<p>These are the standard errors for the intercept and each predictor. Here I add the coefficients and standard errors to a data frame and use them to compute <em>t</em>-values, associated <em>p</em>-values, and confidence intervals.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load library</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create regression table</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">Predictor =</span> <span class="fu">c</span>(<span class="st">"Intercept"</span>, <span class="st">"Ability"</span>, <span class="st">"Motivation"</span>, <span class="st">"Previous Coursework"</span>, <span class="st">"Family Background"</span>),</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">B =</span> <span class="fu">c</span>(b_0, b),</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">SE =</span> se</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">t =</span> <span class="fu">round</span>(B <span class="sc">/</span>SE, <span class="dv">3</span>),</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">p =</span> <span class="fu">round</span>(<span class="dv">2</span> <span class="sc">*</span> <span class="fu">pt</span>(<span class="sc">-</span><span class="fu">abs</span>(t), <span class="at">df =</span> <span class="dv">995</span>), <span class="dv">5</span>),</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">CI =</span> <span class="fu">paste0</span>(<span class="st">"("</span>, <span class="fu">round</span>(B <span class="sc">+</span> <span class="fu">qt</span>(.<span class="dv">025</span>, <span class="at">df =</span> <span class="dv">995</span>)<span class="sc">*</span>SE, <span class="dv">3</span>), <span class="st">", "</span>, <span class="fu">round</span>(B <span class="sc">+</span> <span class="fu">qt</span>(.<span class="dv">975</span>, <span class="at">df =</span> <span class="dv">995</span>)<span class="sc">*</span>SE, <span class="dv">3</span>), <span class="st">")"</span>)</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["Predictor"],"name":[1],"type":["chr"],"align":["left"]},{"label":["B"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["SE"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["t"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["CI"],"name":[6],"type":["chr"],"align":["left"]}],"data":[{"1":"Intercept","2":"6.43375597","3":"1.69169512","4":"3.803","5":"0.00015","6":"(3.114, 9.753)"},{"1":"Ability","2":"0.36737330","3":"0.01550209","4":"23.698","5":"0.00000","6":"(0.337, 0.398)"},{"1":"Motivation","2":"0.01257721","3":"0.02086693","4":"0.603","5":"0.54665","6":"(-0.028, 0.054)"},{"1":"Previous Coursework","2":"1.55001342","3":"0.11957235","4":"12.963","5":"0.00000","6":"(1.315, 1.785)"},{"1":"Family Background","2":"0.69497334","3":"0.21755534","4":"3.194","5":"0.00145","6":"(0.268, 1.122)"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p><br></p>
</section>
</section>
<section id="standardized-regression-from-summaries" class="level1">
<h1>Standardized Regression from Summaries</h1>
<p>We can also compute pertinent values from the standardized regression coefficients in a similar manner; in fact it is easier since there is no intercept to compute in a standardized regression. In a standardized regression, the coefficients are based on the centered and scaled data. Similarly, the correlation matrix is a scaled version of the covariance matrix (which represents the centered data). This allows us to also use the correlation matrices in the set of normal equations:</p>
<p><span class="math display">\[
\mathrm{Cor}(X,X)\mathbf{b^*} = \mathrm{Cor}(X,y)
\]</span></p>
<p>Here we use the notation <span class="math inline">\(\mathbf{b^*}\)</span> to differentiate these predictor estimates from the unstandardized estimates. We can solve this for <span class="math inline">\(\mathbf{b^*}\)</span>:</p>
<p><span class="math display">\[
\mathbf{b^*} = \mathrm{Cor}(X,X)^{-1}\mathrm{Cor}(X,y)
\]</span></p>
<p>This reminds us that the regression coefficients in a standardized regression are correlations (or partial correlations in the multiple regression) between a predictor and the outcome. Here we us the original correlation matrix to compute the standardized regression coefficients:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute standardized coefficients</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>b_star <span class="ot">=</span> <span class="fu">solve</span>(corrs[<span class="sc">-</span><span class="dv">1</span> , <span class="sc">-</span><span class="dv">1</span>]) <span class="sc">%*%</span> corrs[<span class="dv">1</span> , <span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>]</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>b_star</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           [,1]
[1,] 0.55105995
[2,] 0.01257721
[3,] 0.31000268
[4,] 0.06949733</code></pre>
</div>
</div>
<p>Writing the fitted equation:</p>
<p><span class="math display">\[
\begin{split}
\hat{z}_{\mathrm{Achievement}_i} = &amp;0.551(z_{\mathrm{Ability}_i}) + 0.012(z_{\mathrm{Motivation}_i}) + \\
&amp;0.310(z_{\mathrm{Coursework~}_i}) + 0.069(z_{\mathrm{Family~Background}_i})
\end{split}
\]</span></p>
<p>We can also compute the associated standard errors using the following:</p>
<p><span class="math display">\[
\mathrm{SE}_{\mathrm{Std}} = \mathrm{SE}_{\mathrm{Unstd}} \bigg(\frac{b_{\mathrm{Unstd}}}{b_{\mathrm{Std}}}\bigg)
\]</span></p>
<p>In our example,</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute SEs</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>se[<span class="sc">-</span><span class="dv">1</span>] <span class="sc">*</span> b_star <span class="sc">/</span> b</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           [,1]
[1,] 0.02325314
[2,] 0.02086693
[3,] 0.02391447
[4,] 0.02175553</code></pre>
</div>
</div>
<p>Here we had to remove the first element in the <code>se</code> object since it was related to the intercept. Using the estimates from the standardized regresion, the <em>t</em>-values and associated <em>p</em>-values are identical to those from the standardized model. In practice, if you are reporting standardized coefficients, it is typical to report the unstandardized estimates and standard errors, the standardized estimates, and the <em>t</em>- and <em>p</em>-values.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="lightable-classic table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Unstandardized and standardized regression coefficients for fitting a model to predict variation in student achievement for n = 1,000 students. </caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Predictor</th>
<th style="text-align: center;" data-quarto-table-cell-role="th"><em>B</em></th>
<th style="text-align: center;" data-quarto-table-cell-role="th"><em>SE</em></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Std. <em>B</em></th>
<th style="text-align: center;" data-quarto-table-cell-role="th"><em>t</em></th>
<th style="text-align: center;" data-quarto-table-cell-role="th"><em>p</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Ability</td>
<td style="text-align: center;">0.37</td>
<td style="text-align: center;">0.02</td>
<td style="text-align: center;">0.551</td>
<td style="text-align: center;">18.50</td>
<td style="text-align: center;">0.00000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Motivation</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">0.02</td>
<td style="text-align: center;">0.013</td>
<td style="text-align: center;">0.50</td>
<td style="text-align: center;">0.61719</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Previous Coursework</td>
<td style="text-align: center;">1.55</td>
<td style="text-align: center;">0.12</td>
<td style="text-align: center;">0.310</td>
<td style="text-align: center;">12.92</td>
<td style="text-align: center;">0.00000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Family Background</td>
<td style="text-align: center;">0.69</td>
<td style="text-align: center;">0.22</td>
<td style="text-align: center;">0.069</td>
<td style="text-align: center;">3.14</td>
<td style="text-align: center;">0.00174</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: center;">6.43</td>
<td style="text-align: center;">1.69</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">3.80</td>
<td style="text-align: center;">0.00015</td>
</tr>
</tbody><tfoot>
<tr class="even">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Note: </span> <sup></sup> R-squared =0.629; Residual Standard Error = 6.10</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>


</div>
</div>
<p><br></p>
</section>
<section id="simulating-data-using-summary-values" class="level1">
<h1>Simulating Data Using Summary Values</h1>
<p>We can also simulate a set of data that mimics the correlation matrix, means, and standard deviations that were reported in the summaries. To do this, we need to make an assumption that the variables are all multivariately normally distributed. If we make this strong assumption, then we can simulate using the <code>mvrnorm()</code> function from the <code>{MASS}</code> package. In this function we need to provide the sample size, the vector of means (for the outcome and predictors), and the variance-covariance matrix of all the variables.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>MASS<span class="sc">::</span><span class="fu">mvrnorm</span>(<span class="at">n =</span> <span class="dv">1000</span>, <span class="at">mu =</span> means, <span class="at">Sigma =</span> covs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This will draw a sample from a population where the variables have those means and variance-covariance matrix. This means that the data we draw will likely not have the same means, SDs, or correlations. If we want the data to reproduce the summary values exactly, we add the argument <code>empirical=TRUE</code>. Here we do this and assign the data to the <code>sim_dat</code> object</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate the data</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>sim_dat <span class="ot">=</span> MASS<span class="sc">::</span><span class="fu">mvrnorm</span>(<span class="at">n =</span> <span class="dv">1000</span>, <span class="at">mu =</span> means, <span class="at">Sigma =</span> covs, <span class="at">empirical =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This is a matrix object, so we convert it to a data frame and also assign column names so the data are easier to use in our functions.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to data frame</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>sim_dat <span class="ot">=</span> <span class="fu">data.frame</span>(sim_dat)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Change column names</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(sim_dat) <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"achieve"</span>, <span class="st">"ability"</span>, <span class="st">"motivation"</span>, <span class="st">"coursework"</span>, <span class="st">"fam_back"</span>)</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a><span class="co"># View data</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(sim_dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["achieve"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["ability"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["motivation"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["coursework"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["fam_back"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"48.88586","2":"102.37781","3":"38.93417","4":"3.083245","5":"-1.6098535","_rn_":"1"},{"1":"42.18020","2":"89.24882","3":"31.89290","4":"4.330611","5":"-0.6601947","_rn_":"2"},{"1":"58.85591","2":"104.00995","3":"50.52801","4":"2.200933","5":"1.1386242","_rn_":"3"},{"1":"59.11396","2":"120.42658","3":"64.54716","4":"7.279797","5":"0.1060942","_rn_":"4"},{"1":"47.21073","2":"106.45108","3":"65.29760","4":"5.073872","5":"-1.2985168","_rn_":"5"},{"1":"54.01036","2":"89.79483","3":"52.66398","4":"2.396018","5":"0.6197709","_rn_":"6"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Now we can check that the summaries are being reproduced.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute means and SDs</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>sim_dat <span class="sc">|&gt;</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">across</span>(<span class="at">.cols =</span> <span class="fu">everything</span>(), <span class="at">.fns =</span> <span class="fu">list</span>(<span class="at">Mean =</span> mean, <span class="at">SD =</span> sd))</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["achieve_Mean"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["achieve_SD"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["ability_Mean"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["ability_SD"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["motivation_Mean"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["motivation_SD"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["coursework_Mean"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["coursework_SD"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["fam_back_Mean"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["fam_back_SD"],"name":[10],"type":["dbl"],"align":["right"]}],"data":[{"1":"50","2":"10","3":"100","4":"15","5":"50","6":"10","7":"4","8":"2","9":"0","10":"1"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute correlation matrix</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>sim_dat <span class="sc">|&gt;</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  corrr<span class="sc">::</span><span class="fu">correlate</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["term"],"name":[1],"type":["chr"],"align":["left"]},{"label":["achieve"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["ability"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["motivation"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["coursework"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["fam_back"],"name":[6],"type":["dbl"],"align":["right"]}],"data":[{"1":"achieve","2":"NA","3":"0.737","4":"0.255","5":"0.615","6":"0.417"},{"1":"ability","2":"0.737","3":"NA","4":"0.205","5":"0.498","6":"0.417"},{"1":"motivation","2":"0.255","3":"0.205","4":"NA","5":"0.375","6":"0.190"},{"1":"coursework","2":"0.615","3":"0.498","4":"0.375","5":"NA","6":"0.372"},{"1":"fam_back","2":"0.417","3":"0.417","4":"0.190","5":"0.372","6":"NA"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Finally, we should be able to reproduce the regression estimates we have computed.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit unstandardized model</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>lm_unstd <span class="ot">=</span> <span class="fu">lm</span>(achieve <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> ability <span class="sc">+</span> motivation <span class="sc">+</span> coursework <span class="sc">+</span> fam_back, <span class="at">data =</span> sim_dat)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load broom library</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Model-level output</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(lm_unstd) <span class="sc">|&gt;</span></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width =</span> <span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic   p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.629         0.627  6.10      422. 1.89e-212     4 -3225. 6463. 6492.
  deviance df.residual  nobs
     &lt;dbl&gt;       &lt;int&gt; &lt;int&gt;
1   37066.         995  1000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficient-level output</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(lm_unstd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["term"],"name":[1],"type":["chr"],"align":["left"]},{"label":["estimate"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["std.error"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["statistic"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p.value"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"(Intercept)","2":"6.43375597","3":"1.69169512","4":"3.8031415","5":"1.515734e-04"},{"1":"ability","2":"0.36737330","3":"0.01550209","4":"23.6983023","5":"8.533216e-99"},{"1":"motivation","2":"0.01257721","3":"0.02086693","4":"0.6027341","5":"5.468229e-01"},{"1":"coursework","2":"1.55001342","3":"0.11957235","4":"12.9629756","5":"1.271593e-35"},{"1":"fam_back","2":"0.69497334","3":"0.21755534","4":"3.1944670","5":"1.444932e-03"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Standardized model</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>sim_dat <span class="sc">|&gt;</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale</span>() <span class="sc">|&gt;</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(<span class="at">formula =</span> achieve <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> ability <span class="sc">+</span> motivation <span class="sc">+</span> coursework <span class="sc">+</span> fam_back) <span class="sc">|&gt;</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">|&gt;</span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(term <span class="sc">!=</span> <span class="st">"(Intercept)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["term"],"name":[1],"type":["chr"],"align":["left"]},{"label":["estimate"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["std.error"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["statistic"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p.value"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"ability","2":"0.55105995","3":"0.02325314","4":"23.6983023","5":"8.533216e-99"},{"1":"motivation","2":"0.01257721","3":"0.02086693","4":"0.6027341","5":"5.468229e-01"},{"1":"coursework","2":"0.31000268","3":"0.02391447","4":"12.9629756","5":"1.271593e-35"},{"1":"fam_back","2":"0.06949733","3":"0.02175553","4":"3.1944670","5":"1.444932e-03"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>