{
  "hash": "78b253c597b11fb2eceb5069027decb9",
  "result": {
    "markdown": "---\ntitle: \"A Regression Example\"\nformat:\n  html:\n    code-copy: true\n    code-fold: false\n    highlight-style: zenburn\n    df-print: paged\n    css: [\"../assets/style.css\", \"../assets/notes.css\", \"../assets/table-styles.css\"]\ndate: 08-05-2022\nbibliography: '../assets/epsy8264.bib'\ncsl: '../assets/apa-single-spaced.csl'\n---\n\n::: {.cell}\n\n:::\n\n\n---\n\nIn this document we will use the data in [contraception.csv](https://github.com/zief0002/epsy-8264/raw/master/data/contraception.csv) to examine whether female education level explains variation in contraceptive useage after controlling for GNI.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Load libraries\nlibrary(tidyverse)\nlibrary(ggExtra)\nlibrary(broom)\n\n# Import data\ncontraception = read_csv(\"https://github.com/zief0002/epsy-8264/raw/master/data/contraception.csv\")\n\n# View data\ncontraception\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"country\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"region\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"contraceptive\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"educ_female\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"gni\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"Algeria\",\"2\":\"Middle East and North Africa\",\"3\":\"57\",\"4\":\"5.9\",\"5\":\"High\"},{\"1\":\"Austria\",\"2\":\"Europe and Central Asia\",\"3\":\"66\",\"4\":\"8.9\",\"5\":\"High\"},{\"1\":\"Azerbaijan\",\"2\":\"Europe and Central Asia\",\"3\":\"55\",\"4\":\"10.5\",\"5\":\"High\"},{\"1\":\"Bangladesh\",\"2\":\"South Asia\",\"3\":\"62\",\"4\":\"4.6\",\"5\":\"Low\"},{\"1\":\"Belgium\",\"2\":\"Europe and Central Asia\",\"3\":\"67\",\"4\":\"10.5\",\"5\":\"High\"},{\"1\":\"Belize\",\"2\":\"Latin America and the Caribbean\",\"3\":\"51\",\"4\":\"9.2\",\"5\":\"High\"},{\"1\":\"Benin\",\"2\":\"Sub-Saharan Africa\",\"3\":\"16\",\"4\":\"2.0\",\"5\":\"Low\"},{\"1\":\"Bolivia\",\"2\":\"Latin America and the Caribbean\",\"3\":\"67\",\"4\":\"8.4\",\"5\":\"Low\"},{\"1\":\"Bosnia and Herzegovina\",\"2\":\"Europe and Central Asia\",\"3\":\"46\",\"4\":\"7.2\",\"5\":\"High\"},{\"1\":\"Botswana\",\"2\":\"Sub-Saharan Africa\",\"3\":\"53\",\"4\":\"8.7\",\"5\":\"High\"},{\"1\":\"Bulgaria\",\"2\":\"Europe and Central Asia\",\"3\":\"69\",\"4\":\"10.6\",\"5\":\"High\"},{\"1\":\"Burkina Faso\",\"2\":\"Sub-Saharan Africa\",\"3\":\"32\",\"4\":\"1.9\",\"5\":\"Low\"},{\"1\":\"Burundi\",\"2\":\"Sub-Saharan Africa\",\"3\":\"29\",\"4\":\"2.2\",\"5\":\"Low\"},{\"1\":\"Cambodia\",\"2\":\"East Asia and Pacific\",\"3\":\"56\",\"4\":\"3.2\",\"5\":\"Low\"},{\"1\":\"Cameroon\",\"2\":\"Sub-Saharan Africa\",\"3\":\"34\",\"4\":\"5.1\",\"5\":\"Low\"},{\"1\":\"Canada\",\"2\":\"North America\",\"3\":\"85\",\"4\":\"12.3\",\"5\":\"High\"},{\"1\":\"Chad\",\"2\":\"Sub-Saharan Africa\",\"3\":\"6\",\"4\":\"0.6\",\"5\":\"Low\"},{\"1\":\"Chile\",\"2\":\"Latin America and the Caribbean\",\"3\":\"76\",\"4\":\"9.6\",\"5\":\"High\"},{\"1\":\"Colombia\",\"2\":\"Latin America and the Caribbean\",\"3\":\"81\",\"4\":\"7.0\",\"5\":\"High\"},{\"1\":\"Congo, Democratic Republic\",\"2\":\"Sub-Saharan Africa\",\"3\":\"20\",\"4\":\"2.1\",\"5\":\"Low\"},{\"1\":\"Costa Rica\",\"2\":\"Latin America and the Caribbean\",\"3\":\"78\",\"4\":\"8.4\",\"5\":\"High\"},{\"1\":\"Croatia\",\"2\":\"Europe and Central Asia\",\"3\":\"69\",\"4\":\"10.5\",\"5\":\"High\"},{\"1\":\"Czech Republic\",\"2\":\"Europe and Central Asia\",\"3\":\"86\",\"4\":\"12.1\",\"5\":\"High\"},{\"1\":\"Dominican Republic\",\"2\":\"Latin America and the Caribbean\",\"3\":\"70\",\"4\":\"7.7\",\"5\":\"High\"},{\"1\":\"Ecuador\",\"2\":\"Latin America and the Caribbean\",\"3\":\"80\",\"4\":\"7.4\",\"5\":\"High\"},{\"1\":\"Egypt, Arab Republic\",\"2\":\"Middle East and North Africa\",\"3\":\"59\",\"4\":\"5.3\",\"5\":\"Low\"},{\"1\":\"El Salvador\",\"2\":\"Latin America and the Caribbean\",\"3\":\"72\",\"4\":\"6.1\",\"5\":\"Low\"},{\"1\":\"Ethiopia\",\"2\":\"Sub-Saharan Africa\",\"3\":\"40\",\"4\":\"1.4\",\"5\":\"Low\"},{\"1\":\"France\",\"2\":\"Europe and Central Asia\",\"3\":\"78\",\"4\":\"10.9\",\"5\":\"High\"},{\"1\":\"Ghana\",\"2\":\"Sub-Saharan Africa\",\"3\":\"31\",\"4\":\"5.9\",\"5\":\"Low\"},{\"1\":\"Greece\",\"2\":\"Europe and Central Asia\",\"3\":\"76\",\"4\":\"9.9\",\"5\":\"High\"},{\"1\":\"Guinea\",\"2\":\"Sub-Saharan Africa\",\"3\":\"9\",\"4\":\"0.8\",\"5\":\"Low\"},{\"1\":\"Haiti\",\"2\":\"Latin America and the Caribbean\",\"3\":\"34\",\"4\":\"3.2\",\"5\":\"Low\"},{\"1\":\"Honduras\",\"2\":\"Latin America and the Caribbean\",\"3\":\"73\",\"4\":\"5.3\",\"5\":\"Low\"},{\"1\":\"Hungary\",\"2\":\"Europe and Central Asia\",\"3\":\"62\",\"4\":\"11.2\",\"5\":\"High\"},{\"1\":\"India\",\"2\":\"South Asia\",\"3\":\"54\",\"4\":\"3.2\",\"5\":\"Low\"},{\"1\":\"Indonesia\",\"2\":\"East Asia and Pacific\",\"3\":\"61\",\"4\":\"6.9\",\"5\":\"Low\"},{\"1\":\"Iraq\",\"2\":\"Middle East and North Africa\",\"3\":\"53\",\"4\":\"4.4\",\"5\":\"High\"},{\"1\":\"Italy\",\"2\":\"Europe and Central Asia\",\"3\":\"65\",\"4\":\"9.7\",\"5\":\"High\"},{\"1\":\"Jamaica\",\"2\":\"Latin America and the Caribbean\",\"3\":\"73\",\"4\":\"9.8\",\"5\":\"High\"},{\"1\":\"Japan\",\"2\":\"East Asia and Pacific\",\"3\":\"40\",\"4\":\"11.2\",\"5\":\"High\"},{\"1\":\"Jordan\",\"2\":\"Middle East and North Africa\",\"3\":\"52\",\"4\":\"9.4\",\"5\":\"High\"},{\"1\":\"Kazakhstan\",\"2\":\"Europe and Central Asia\",\"3\":\"55\",\"4\":\"10.2\",\"5\":\"High\"},{\"1\":\"Kenya\",\"2\":\"Sub-Saharan Africa\",\"3\":\"61\",\"4\":\"5.4\",\"5\":\"Low\"},{\"1\":\"Korea, Republic\",\"2\":\"East Asia and Pacific\",\"3\":\"80\",\"4\":\"11.1\",\"5\":\"High\"},{\"1\":\"Lao PDR\",\"2\":\"East Asia and Pacific\",\"3\":\"54\",\"4\":\"3.8\",\"5\":\"Low\"},{\"1\":\"Lebanon\",\"2\":\"Middle East and North Africa\",\"3\":\"55\",\"4\":\"7.6\",\"5\":\"High\"},{\"1\":\"Lesotho\",\"2\":\"Sub-Saharan Africa\",\"3\":\"60\",\"4\":\"6.8\",\"5\":\"Low\"},{\"1\":\"Liberia\",\"2\":\"Sub-Saharan Africa\",\"3\":\"31\",\"4\":\"2.3\",\"5\":\"Low\"},{\"1\":\"Madagascar\",\"2\":\"Sub-Saharan Africa\",\"3\":\"48\",\"4\":\"4.8\",\"5\":\"Low\"},{\"1\":\"Malawi\",\"2\":\"Sub-Saharan Africa\",\"3\":\"59\",\"4\":\"3.4\",\"5\":\"Low\"},{\"1\":\"Malaysia\",\"2\":\"East Asia and Pacific\",\"3\":\"52\",\"4\":\"9.2\",\"5\":\"High\"},{\"1\":\"Maldives\",\"2\":\"South Asia\",\"3\":\"19\",\"4\":\"5.4\",\"5\":\"High\"},{\"1\":\"Mali\",\"2\":\"Sub-Saharan Africa\",\"3\":\"16\",\"4\":\"1.4\",\"5\":\"Low\"},{\"1\":\"Malta\",\"2\":\"Middle East and North Africa\",\"3\":\"86\",\"4\":\"9.5\",\"5\":\"High\"},{\"1\":\"Mauritius\",\"2\":\"Sub-Saharan Africa\",\"3\":\"64\",\"4\":\"8.0\",\"5\":\"High\"},{\"1\":\"Mexico\",\"2\":\"Latin America and the Caribbean\",\"3\":\"67\",\"4\":\"8.1\",\"5\":\"High\"},{\"1\":\"Moldova\",\"2\":\"Europe and Central Asia\",\"3\":\"60\",\"4\":\"9.6\",\"5\":\"Low\"},{\"1\":\"Mongolia\",\"2\":\"East Asia and Pacific\",\"3\":\"55\",\"4\":\"8.5\",\"5\":\"Low\"},{\"1\":\"Morocco\",\"2\":\"Middle East and North Africa\",\"3\":\"71\",\"4\":\"3.2\",\"5\":\"Low\"},{\"1\":\"Mozambique\",\"2\":\"Sub-Saharan Africa\",\"3\":\"27\",\"4\":\"0.8\",\"5\":\"Low\"},{\"1\":\"Namibia\",\"2\":\"Sub-Saharan Africa\",\"3\":\"56\",\"4\":\"6.3\",\"5\":\"High\"},{\"1\":\"Nepal\",\"2\":\"South Asia\",\"3\":\"53\",\"4\":\"2.4\",\"5\":\"Low\"},{\"1\":\"Nicaragua\",\"2\":\"Latin America and the Caribbean\",\"3\":\"80\",\"4\":\"4.8\",\"5\":\"Low\"},{\"1\":\"Niger\",\"2\":\"Sub-Saharan Africa\",\"3\":\"11\",\"4\":\"0.8\",\"5\":\"Low\"},{\"1\":\"Nigeria\",\"2\":\"Sub-Saharan Africa\",\"3\":\"28\",\"4\":\"4.2\",\"5\":\"Low\"},{\"1\":\"Pakistan\",\"2\":\"South Asia\",\"3\":\"34\",\"4\":\"3.3\",\"5\":\"Low\"},{\"1\":\"Panama\",\"2\":\"Latin America and the Caribbean\",\"3\":\"63\",\"4\":\"9.6\",\"5\":\"High\"},{\"1\":\"Paraguay\",\"2\":\"Latin America and the Caribbean\",\"3\":\"68\",\"4\":\"7.5\",\"5\":\"High\"},{\"1\":\"Philippines\",\"2\":\"East Asia and Pacific\",\"3\":\"54\",\"4\":\"8.8\",\"5\":\"Low\"},{\"1\":\"Portugal\",\"2\":\"Europe and Central Asia\",\"3\":\"74\",\"4\":\"8.0\",\"5\":\"High\"},{\"1\":\"Romania\",\"2\":\"Europe and Central Asia\",\"3\":\"70\",\"4\":\"10.4\",\"5\":\"High\"},{\"1\":\"Rwanda\",\"2\":\"Sub-Saharan Africa\",\"3\":\"53\",\"4\":\"3.1\",\"5\":\"Low\"},{\"1\":\"Sao Tome and Principe\",\"2\":\"Sub-Saharan Africa\",\"3\":\"41\",\"4\":\"4.0\",\"5\":\"Low\"},{\"1\":\"Senegal\",\"2\":\"Sub-Saharan Africa\",\"3\":\"28\",\"4\":\"3.4\",\"5\":\"Low\"},{\"1\":\"Serbia\",\"2\":\"Europe and Central Asia\",\"3\":\"58\",\"4\":\"9.2\",\"5\":\"High\"},{\"1\":\"Sierra Leone\",\"2\":\"Sub-Saharan Africa\",\"3\":\"23\",\"4\":\"2.0\",\"5\":\"Low\"},{\"1\":\"Slovak Republic\",\"2\":\"Europe and Central Asia\",\"3\":\"80\",\"4\":\"11.6\",\"5\":\"High\"},{\"1\":\"Slovenia\",\"2\":\"Europe and Central Asia\",\"3\":\"79\",\"4\":\"11.8\",\"5\":\"High\"},{\"1\":\"South Africa\",\"2\":\"Sub-Saharan Africa\",\"3\":\"55\",\"4\":\"9.8\",\"5\":\"High\"},{\"1\":\"Spain\",\"2\":\"Europe and Central Asia\",\"3\":\"71\",\"4\":\"9.5\",\"5\":\"High\"},{\"1\":\"Suriname\",\"2\":\"Latin America and the Caribbean\",\"3\":\"48\",\"4\":\"7.3\",\"5\":\"High\"},{\"1\":\"Swaziland\",\"2\":\"Sub-Saharan Africa\",\"3\":\"66\",\"4\":\"7.4\",\"5\":\"Low\"},{\"1\":\"Tajikistan\",\"2\":\"Europe and Central Asia\",\"3\":\"29\",\"4\":\"10.0\",\"5\":\"Low\"},{\"1\":\"Tanzania\",\"2\":\"Sub-Saharan Africa\",\"3\":\"38\",\"4\":\"4.5\",\"5\":\"Low\"},{\"1\":\"Thailand\",\"2\":\"East Asia and Pacific\",\"3\":\"78\",\"4\":\"7.0\",\"5\":\"High\"},{\"1\":\"Togo\",\"2\":\"Sub-Saharan Africa\",\"3\":\"20\",\"4\":\"3.3\",\"5\":\"Low\"},{\"1\":\"Tunisia\",\"2\":\"Middle East and North Africa\",\"3\":\"63\",\"4\":\"5.5\",\"5\":\"Low\"},{\"1\":\"Uganda\",\"2\":\"Sub-Saharan Africa\",\"3\":\"42\",\"4\":\"4.3\",\"5\":\"Low\"},{\"1\":\"Ukraine\",\"2\":\"Europe and Central Asia\",\"3\":\"65\",\"4\":\"11.2\",\"5\":\"Low\"},{\"1\":\"United Kingdom\",\"2\":\"Europe and Central Asia\",\"3\":\"84\",\"4\":\"12.8\",\"5\":\"High\"},{\"1\":\"Uruguay\",\"2\":\"Latin America and the Caribbean\",\"3\":\"80\",\"4\":\"8.7\",\"5\":\"High\"},{\"1\":\"Venezuela, RB\",\"2\":\"Latin America and the Caribbean\",\"3\":\"75\",\"4\":\"8.7\",\"5\":\"High\"},{\"1\":\"Vietnam\",\"2\":\"East Asia and Pacific\",\"3\":\"76\",\"4\":\"5.2\",\"5\":\"Low\"},{\"1\":\"Yemen, Republic\",\"2\":\"Middle East and North Africa\",\"3\":\"34\",\"4\":\"1.2\",\"5\":\"Low\"},{\"1\":\"Zambia\",\"2\":\"Sub-Saharan Africa\",\"3\":\"49\",\"4\":\"5.8\",\"5\":\"Low\"},{\"1\":\"Zimbabwe\",\"2\":\"Sub-Saharan Africa\",\"3\":\"67\",\"4\":\"6.7\",\"5\":\"Low\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# IF you want to see all the variables\n#print(contraception, width = Inf)\n```\n:::\n\n\n## Examine the Data\n\nWe need to correctly specify the model. Since we have no theory to guide us, this is done empirically by looking at the data.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Create scatterplot\np = ggplot(data = contraception, aes(x = educ_female, y = contraceptive)) + \n   geom_point() +\n   geom_smooth(method = \"lm\", se = FALSE) +\n   theme_bw() +\n   labs(\n      x = \"Female education level\",\n      y = \"Contraceptive useage\"\n   ) \n\n# Add marginal density plots\nggMarginal(p, type = \"density\")\n\n# Condition the relationship on GNI\nggplot(data = contraception, aes(x = educ_female, y = contraceptive, color = gni)) + \n   geom_point() +\n   geom_smooth(method = \"lm\", se = FALSE) +\n   theme_bw() +\n   labs(\n      x = \"Female education level\",\n      y = \"Contraceptive useage\"\n   ) +\n   facet_wrap(~gni)\n```\n\n::: {.cell-output-display}\n![](handout-regression-example-in-practice_files/figure-html/unnamed-chunk-3-1.png){fig-align='center' width=45%}\n:::\n\n::: {.cell-output-display}\n![](handout-regression-example-in-practice_files/figure-html/unnamed-chunk-3-2.png){fig-align='center' width=45%}\n:::\n:::\n\n\n- Should we include main-effects only? Or an interaction?\n- Is there non-linearity to account for (e.g., transformations)? Or does it look linear?\n\n\n<br />\n\n\n## Use Matrix Algebra to Compute Coefficient Estimates\n\n$$\n\\mathbf{b} = (\\mathbf{X}^\\intercal\\mathbf{X})^{-1} \\mathbf{X}^\\intercal\\mathbf{y}\n$$\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Store values\nn = nrow(contraception) #Sample size\nk = 2 #Number of predictors\n\n\n# Create outcome vector\ny = contraception$contraceptive\n\n# Create dummy variable for GNI\ncontraception = contraception %>%\n   mutate(\n      high_gni = if_else(gni == \"High\", 1, 0)\n      )\n\n# Create design matrix\nX = matrix(\n   data = c(rep(1, n), contraception$educ_female, contraception$high_gni),\n   ncol = 3\n)\n\n# Compute b vector\nb = solve(t(X) %*% X) %*% t(X) %*% y\nb\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          [,1]\n[1,] 27.021387\n[2,]  4.088735\n[3,]  1.608766\n```\n:::\n:::\n\n\nThus the fitted regression equation is:\n\n$$\n\\widehat{\\mathrm{Contraceptive~Use}}_i = 27.02 + 4.09(\\mathrm{Female~Education~Level}_i) + 1.60(\\mathrm{High~GNI}_i)\n$$\n\n<br />\n\n\n## Compute Residual Standard Error \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Compute e vector\ne = y - X %*% b\n\n# Compute s_e\ns_e = sqrt((t(e) %*% e) / (n - k - 1))\ns_e\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         [,1]\n[1,] 14.39792\n```\n:::\n:::\n\n\nThus the residual standard error (a.k.a., the root mean square error; RMSE) is:\n\n$$\ns_e = 14.40\n$$\n\n<br />\n\n\n## Compute Variance--Covariance Matrix for the Coefficients\n\n$$\n\\mathrm{Var}(\\mathbf{b}) = s^2_e(\\mathbf{X}^\\intercal\\mathbf{X})^{-1} \n$$\n\nwhere $s^2_e = \\frac{\\mathbf{e}^\\intercal\\mathbf{e}}{n-k-1}$\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Compute varaince-covariance matrix of b\nV = as.numeric(s_e^2) * solve(t(X) %*% X)\nV\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          [,1]       [,2]      [,3]\n[1,] 12.414688 -1.8783934  4.782603\n[2,] -1.878393  0.4267136 -2.028306\n[3,]  4.782603 -2.0283060 18.197825\n```\n:::\n\n```{.r .cell-code}\n# Compute SEs for b\nsqrt(diag(V))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3.5234483 0.6532332 4.2658909\n```\n:::\n:::\n\n\n\nThus\n\n$$\n\\mathrm{SE}(b_0) = 3.52 \\qquad \\mathrm{SE}(b_1) = 0.65 \\qquad \\mathrm{SE}(b_2) = 4.27\n$$\n\n<br />\n\n\n## Coefficient-Level Inference\n\nHere we will focus on the effects of female education level since it is our focal predictor. (GNI is a control.) Note this is the second effect in the **b** vector and in the **V** matrix. We will test the hypothesis:\n\n$$\nH_0: \\beta_{\\mathrm{Education}} = 0\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Compute t-value\nt_0 = (b[2] - 0) / sqrt(V[2, 2])\nt_0\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6.259228\n```\n:::\n\n```{.r .cell-code}\n# Evaluate t-value\ndf = n - k - 1\np = 2* (1 - pt(abs(t_0), df = df))\np\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.00000001143799\n```\n:::\n:::\n\n\nHere,\n\n$$\nt(94) = 6.26,~p=0.0000000114\n$$\n\nThe evidence suggests that the data are not very compatible with the hypothesis that there is no effect of female education level on contraceptive useage, after controlling for differences in GNI.\n\n<br />\n\n\n## Statistical Inference: Confidence Intervals for the Coefficients\n\nFrom the hypothesis test, we believe there is an effect of female education level on contraceptive useage, after controlling for differences in GNI. What is that effect? To answer this we will compute a 95% CI for the effect of female education.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Compute critical value\nt_star = qt(.025, df = df)\n\n# Compute CI\nb[2] - abs(t_star) * sqrt(V[2, 2])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2.791725\n```\n:::\n\n```{.r .cell-code}\nb[2] + abs(t_star) * sqrt(V[2, 2])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5.385745\n```\n:::\n:::\n\n\nThe 95% CI indicates that the population effect of female education level on contraceptive useage, after controlling for differences in GNI is between 2.79 and 5.39. \n\n<br />\n\n\n# ANOVA Decompostion\n\nHere we want to partition the sums of squares:\n\n$$\n\\mathrm{SS}_{\\mathrm{Total}} = \\mathrm{SS}_{\\mathrm{Model}} + \\mathrm{SS}_{\\mathrm{Residual}}\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Compute needed values\nmean_y = mean(y)\nhat_y = X %*% b\n\n\n# Compute SS_Total\nss_total = t(y - mean_y) %*% (y - mean_y)\nss_total\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         [,1]\n[1,] 38336.45\n```\n:::\n\n```{.r .cell-code}\n# Compute SS_model\nss_model = t(hat_y - mean_y) %*% (hat_y - mean_y)\nss_model\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         [,1]\n[1,] 18850.25\n```\n:::\n\n```{.r .cell-code}\n# Compute SS_residual\nss_residual = t(y - hat_y) %*% (y - hat_y)\nss_residual\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        [,1]\n[1,] 19486.2\n```\n:::\n:::\n\n\n\nHere:\n\n- $\\mathrm{SS}_{\\mathrm{Total}}=38,336.45$\n- $\\mathrm{SS}_{\\mathrm{Model}}=18,850.25$\n- $\\mathrm{SS}_{\\mathrm{Residual}}=19,486.2$\n\nWe can verify that:\n\n$$\n38,336.45 = 18,850.25 + 19,486.2\n$$\n\nThis can be used to compute the model-level $R^2$ value.\n\n$$\nR^2 = \\frac{\\mathrm{SS}_{\\mathrm{Model}}}{\\mathrm{SS}_{\\mathrm{Total}}}\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Compute R^2\nr2 = ss_model / ss_total\nr2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          [,1]\n[1,] 0.4917057\n```\n:::\n:::\n\n\nThe model explains 49.1% of the variation in contraception usage. \n\n<br />\n\n\n# Model-Level Inference\n\nHere we want to test whether the model explained variation is more than we would expect because of sampling variation, namely \n\n$$\nH_0: \\rho^2=0\n$$\n\nThis is equivalent to testing:\n\n$$\nH_0: \\beta_{\\mathrm{Female~Education}} = \\beta_{\\mathrm{GNI}} = 0\n$$\n\nWe compute an observed *F*-value as:\n\n$$\nF_0 = \\frac{(\\mathbf{Lb}-\\mathbf{c})^\\intercal\\big[\\mathbf{L}(\\mathbf{X}^\\intercal\\mathbf{X})^{-1}\\mathbf{L}^\\intercal\\big]^{-1}(\\mathbf{Lb}-\\mathbf{c})}{q(s^2_e)}\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Create L (hypothesis matrix)\nL = matrix(\n   data = c(0, 1, 0, 0, 0, 1),\n   byrow = TRUE,\n   ncol = 3\n)\n\n# Create vector of hypothesized values\nC = matrix(\n   data = c(0, 0),\n   ncol = 1\n)\n\nq = 2\n\nF_num = t(L %*% b - C) %*% solve(L %*% solve(t(X) %*% X) %*% t(L)) %*% (L %*% b - C)\nF_denom = q * s_e^2\n\nF_0 = F_num / F_denom\nF_0\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         [,1]\n[1,] 45.46611\n```\n:::\n\n```{.r .cell-code}\n# Evaluate F_0\n1 - pf(F_0, df1 = q, df2 = (n - k - 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             [,1]\n[1,] 1.532108e-14\n```\n:::\n:::\n\n\nHere,\n\n$$\nF(2, 94) = 45.47,~p=0.0000000000000153\n$$\n\nThe data are not very compatible with the hypothesis that the model explains no variation in the outcome. It is likely there is a controlled effect of female education level, or GNI (or both) on contraceptive usage. That is, the explained variation of 49.1\\% is more than we would expect because of chance.\n\n<br />\n\n\n# In Practice\n\nIn practice, you would simply use built-in R functions to do all of this. Note that you can use a categorical variable in the `lm()` function directly (without dummy coding it beforehand), but it will pick the reference category for you (alphabetically). For example:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Fit model\nlm.1 = lm(contraceptive ~ 1 + educ_female + gni, data = contraception)\n\n# Coefficient-level output\ntidy(lm.1)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"term\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"estimate\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"std.error\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"statistic\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p.value\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"(Intercept)\",\"2\":\"28.630153\",\"3\":\"6.3385897\",\"4\":\"4.516802\",\"5\":\"0.00001821782737\"},{\"1\":\"educ_female\",\"2\":\"4.088735\",\"3\":\"0.6532332\",\"4\":\"6.259228\",\"5\":\"0.00000001143798\"},{\"1\":\"gniLow\",\"2\":\"-1.608766\",\"3\":\"4.2658909\",\"4\":\"-0.377123\",\"5\":\"0.70693222349564\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# Coempute confidence intervals for coefficients\nconfint(lm.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 2.5 %    97.5 %\n(Intercept)  16.044734 41.215571\neduc_female   2.791725  5.385745\ngniLow      -10.078792  6.861261\n```\n:::\n\n```{.r .cell-code}\n# Model-level output\nglance(lm.1)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"r.squared\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"adj.r.squared\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sigma\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"statistic\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p.value\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"df\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"logLik\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"AIC\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BIC\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"deviance\"],\"name\":[10],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"df.residual\"],\"name\":[11],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"nobs\"],\"name\":[12],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"0.4917057\",\"2\":\"0.4808909\",\"3\":\"14.39792\",\"4\":\"45.46611\",\"5\":\"1.539636e-14\",\"6\":\"2\",\"7\":\"-394.8205\",\"8\":\"797.6409\",\"9\":\"807.9398\",\"10\":\"19486.2\",\"11\":\"94\",\"12\":\"97\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# ANOVA decomposition\nanova(lm.1)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Df\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Sum Sq\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Mean Sq\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F value\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1\",\"2\":\"18820.76855\",\"3\":\"18820.76855\",\"4\":\"90.7899959\",\"5\":\"1.849680e-15\",\"_rn_\":\"educ_female\"},{\"1\":\"1\",\"2\":\"29.48258\",\"3\":\"29.48258\",\"4\":\"0.1422218\",\"5\":\"7.069322e-01\",\"_rn_\":\"gni\"},{\"1\":\"94\",\"2\":\"19486.20248\",\"3\":\"207.30003\",\"4\":\"NA\",\"5\":\"NA\",\"_rn_\":\"Residuals\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n<br />\n\n\n## Accessing Regression Matrices from lm()\n\nThere are several built-in R functions that allow you to access different regression matrices once you have fitted a model with `lm()`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Access design matrix\nmodel.matrix(lm.1)\n```\n:::\n\n\n```\n   (Intercept) educ_female gniLow\n1            1         5.9      0\n2            1         8.9      0\n3            1        10.5      0\n4            1         4.6      1\n:            :          :       :\n97           1         6.7      1\nattr(,\"assign\")\n[1] 0 1 2\nattr(,\"contrasts\")\nattr(,\"contrasts\")$gni\n[1] \"contr.treatment\"\n```\n\nThe design matrix is given and information about this design matrix is also encoded. There is an attribute \"assign\", an integer vector with an entry for each column in the matrix giving the term in the formula which gave rise to the column. Value 0 corresponds to the intercept (if any), and positive values to terms in the order given by the term.labels attribute of the terms structure corresponding to object. There is also an attribute called \"contrasts\" that identifies any factors (categorical variables) in the model and indicates how the contrast testing (comparison of the factor levels) will be carried out. Here \"contr.treatment\" is used. This compares each level of the factor to the baseline (which is how dummy coding works).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Access coefficient estimates\ncoef(lm.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept) educ_female      gniLow \n  28.630153    4.088735   -1.608766 \n```\n:::\n\n```{.r .cell-code}\n# Access variance-covariance matrix for b\nvcov(lm.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            (Intercept) educ_female     gniLow\n(Intercept)   40.177719  -3.9066994 -22.980428\neduc_female   -3.906699   0.4267136   2.028306\ngniLow       -22.980428   2.0283060  18.197825\n```\n:::\n\n```{.r .cell-code}\n# Access fitted values\nfitted(lm.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       1        2        3        4        5        6        7        8 \n52.75369 65.01990 71.56187 45.82957 71.56187 66.24652 35.19886 61.36676 \n       9       10       11       12       13       14       15       16 \n58.06905 64.20215 71.97075 34.78998 36.01660 40.10534 47.87394 78.92160 \n      17       18       19       20       21       22       23       24 \n29.47463 67.88201 57.25130 35.60773 62.97553 71.56187 78.10385 60.11341 \n      25       26       27       28       29       30       31       32 \n58.88679 48.69168 51.96267 32.74562 73.19737 51.14493 69.10863 30.29238 \n      33       34       35       36       37       38       39       40 \n40.10534 48.69168 74.42399 40.10534 55.23366 46.62059 68.29089 68.69976 \n      41       42       43       44       45       46       47       48 \n74.42399 67.06427 70.33525 49.10056 74.01512 42.55858 59.70454 54.82479 \n      49       50       51       52       53       54       55       56 \n36.42548 46.64732 40.92309 66.24652 50.70932 32.74562 67.47314 61.34004 \n      57       58       59       60       61       62       63       64 \n61.74891 66.27325 61.77564 40.10534 30.29238 54.38919 36.83435 46.64732 \n      65       66       67       68       69       70       71       72 \n30.29238 44.19408 40.51421 67.88201 59.29567 63.00226 61.34004 71.15300 \n      73       74       75       76       77       78       79       80 \n39.69647 43.37633 40.92309 66.24652 35.19886 76.05948 76.87723 68.69976 \n      81       82       83       84       85       86       87       88 \n67.47314 58.47792 57.27803 67.90874 45.42070 57.25130 40.51421 49.50943 \n      89       90       91       92       93       94       95       96 \n44.60295 72.81522 80.96597 64.20215 64.20215 48.28281 31.92787 50.73605 \n      97 \n54.41591 \n```\n:::\n\n```{.r .cell-code}\n# Access raw residuals\nresid(lm.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          1           2           3           4           5           6 \n  4.2463087   0.9801026 -16.5618739  16.1704304  -4.5618739 -15.2465180 \n          7           8           9          10          11          12 \n-19.1988577   5.6332361 -12.0690473 -11.2021503  -2.9707474  -2.7899842 \n         13          14          15          16          17          18 \n -7.0166048  15.8946599 -13.8739373   6.0784025 -23.4746282   8.1179879 \n         19          20          21          22          23          24 \n 23.7486998 -15.6077312  15.0244703  -2.5618739   7.8961495   9.8865851 \n         25          26          27          28          29          30 \n 21.1132057  10.3083157  20.0373274   7.2543835   4.8026319 -20.1449256 \n         31          32          33          34          35          36 \n  6.8913673 -21.2923753  -6.1053401  24.3083157 -12.4239887  13.8946599 \n         37          38          39          40          41          42 \n  5.7663391   6.3794117  -3.2908856   4.3002408 -34.4239887 -15.0642650 \n         43          44          45          46          47          48 \n-15.3352533  11.8994421   5.9848849  11.4414187  -4.7045414   5.1752126 \n         49          50          51          52          53          54 \n -5.4254783   1.3526833  18.0769128 -14.2465180 -31.7093236 -16.7456165 \n         55          56          57          58          59          60 \n 18.5268614   2.6599645   5.2510909  -6.2732463  -6.7756375  30.8946599 \n         61          62          63          64          65          66 \n -3.2923753   1.6108145  16.1656482  33.3526833 -19.2923753 -16.1940755 \n         67          68          69          70          71          72 \n -6.5142136  -4.8820121   8.7043321  -9.0022581  12.6599645  -1.1530004 \n         73          74          75          76          77          78 \n 13.3035334  -2.3763284 -12.9230872  -8.2465180 -12.1988577   3.9405172 \n         79          80          81          82          83          84 \n  2.1227701 -13.6997592   3.5268614 -10.4779208   8.7219714 -38.9087405 \n         85          86          87          88          89          90 \n -7.4206961  20.7486998 -20.5142136  13.4905686  -2.6029490  -7.8152229 \n         91          92          93          94          95          96 \n  3.0340348  15.7978497  10.7978497  27.7171892   2.0721306  -1.7360520 \n         97 \n 12.5840862 \n```\n:::\n:::\n",
    "supporting": [
      "handout-regression-example-in-practice_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}