---
title: "`r paste(emo::ji('book'), 'Welcome to EPsy 8264')`"
format:
  html:
   css: "../assets/styles.css"
date: 08-05-2022
---


In this class, we will work together to develop a learning community that is inclusive and respectful, and where every student is supported in the learning process. As a class full of diverse individuals (reflected by differences in race, culture, age, religion, gender identity, sexual orientation, socioeconomic background, abilities, professional goals, and other social identities and life experiences) I expect that different students may need different things to support and promote their learning. 

The TAs and I will do everything we can to help with this, but, as we only know what we know, we need you to communicate with us if things are not working for you or you need something we are not providing. I hope you all feel comfortable in helping to promote an inclusive classroom through respecting one another's individual differences, speaking up, and challenging oppressive/problematic ideas. Finally, I look forward to learning from each of you and the experiences you bring to the class.

<br />


## Prerequisites

The pre-requisites for this course are *EPsy 8251* and *EPsy 8252*. Prerequisite knowledge include topics from a basic statistics course: 

- Foundational topics in data analysis;
  + Design (e.g., random assignment and random sampling)
  + Descriptive statistics and plots
  + One- and two-sample tests

And, topics from *EPsy 8251: Methods in Data Analysis for Educational Research I*:   
  
- Statistical Computation
  + Using R
  + Data wrangling/manipulation
  + Plotting
- Correlation;
- Simple regression analysis;
  + Model-level and coefficient-level interpretation
  + Ordinary least squares estimation
  + Standardized regression
  + Partitioning sums of squares
  + Model-level and coefficient-level inference
  + Assumption checking/residual analysis
- Multiple linear regression
  + Model-level and coefficient-level interpretation and inference
  + Assumption checking/residual analysis
  + Working with categorical predictors (including adjusting *p*-values for multiple tests)
  + Interaction effects
  
And topics from *EPsy 8252: Methods in Data Analysis for Educational Research II*:

- Dealing with nonlinearity;
  + Quadratic effects
  + Log-transformations
- Probability distributions;
  + Probability density
- Maximum likelihood estimation;
- Model selection;
  + Information criteria
- Linear mixed-effects models (cross-sectional/longitudinal)
  + Basic ideas of mixed-effects models
  + Fitting models with random-intercepts and random-slopes
  + Assumptions
  + Likelihood ratio tests
- Generalized linear models
  + Logistic models

<br />


## Resources

For the topics listed, students would be expected to be able to carry out an appropriate data analysis and properly interpret the results. It is also assumed that everyone enrolled in the course has some familiarity with using R. If you need a refresher on any of these topics, see:

- [Computational Toolkit for Educational Scientists](https://zief0002.github.io/toolkit/)
- [Statistical Modeling and Computation for Educational Scientists](https://zief0002.github.io/modeling/) [EPsy 8251 material]
- [EPsy 8252 website](http://zief0002.github.io/epsy-8252/)


